Refactoring metadata to file
JabRef/jabref pull request #10306
Opened 2023-09-03 22:05 UTC by Luggas4you

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-09-03 23:30 UTC, koppor requested changes
Tried it. Works.

Two nitpicks remaining.

2023-09-03 23:30 UTC, koppor commented on src/main/java/org/jabref/gui/exporter/WriteMetadataToLinkedPdfsAction.java
> +            dialogService.notify(Localization.lang("Finished writing metadata for database %0 (%1 succeeded, %2 skipped, %3 errors).",
JabRef uses "library" for .bib files, not "database" as term.

```suggestion
            dialogService.notify(Localization.lang("Finished writing metadata for library %0 (%1 succeeded, %2 skipped, %3 errors).",
```

2023-09-03 23:30 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/WriteMetadataToSinglePdfAction.java
> +
Remove empty line

2023-09-04 08:03 UTC, calixtus approved these changes

2023-09-04 08:17 UTC, calixtus approved these changes

2023-09-04 09:08 UTC, merged