@Tests for EntryComperatorTest
JabRef/jabref pull request #10357
Opened 2023-09-09 12:02 UTC by Luggas4you

Add testPresentFieldsWithKeyField & testPresentFieldsWithoutKeyField for code coverage as well as reducing code. 

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-09-09 20:59 UTC, Siedlerchr approved these changes

2023-09-11 20:36 UTC, koppor requested changes
Added tests look good. However, the refactoring needs to be undone.

2023-09-11 20:36 UTC, koppor commented on src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java
> +    }
I know, this was lots of effort. Please revert this change. The tests were more readable before the update.

2023-09-11 20:36 UTC, koppor commented on src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java
> +    }
This test is OK.

2023-09-11 20:36 UTC, koppor commented on src/test/java/org/jabref/logic/bibtex/comparator/EntryComparatorTest.java
> +        assertEquals(-1, new EntryComparator(true, false, StandardField.AUTHOR).compare(e1, e2));
This test is also ok

2023-09-11 20:36 UTC, koppor commented on src/test/java/org/jabref/logic/bibtex/comparator/FieldComparatorTest.java
> +    }
Nice one!

2023-09-15 16:21 UTC, koppor approved these changes

2023-09-15 16:21 UTC, merged