Change  two check boxes in CleanupPresetPanel.fxml to radio buttons with Toggle Group
JabRef/jabref pull request #10597
Opened 2023-10-28 14:51 UTC by suxiaocha123

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-10-28 15:09 UTC, ThiloteE commented
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>

2023-10-28 21:13 UTC, koppor requested changes
CHANGELOG.md entry is missing.

I get an exception when trying out

![image](https://github.com/JabRef/jabref/assets/1366654/95ef269b-2734-4c0f-ba4d-afbde7a71e33)

2023-10-28 21:13 UTC, koppor commented on src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.fxml
> +   </RadioButton>
Indent seems tob e off. Opening and matching closing tags should be on the same column.

2023-10-28 21:13 UTC, koppor commented on src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.fxml
> +   <RadioButton text="%Convert to BibTeX format (e.g., store publication date in year and month fields)" toggleGroup="$conversionToggleGroup" />
Indent is off here, too.

2023-10-29 12:22 UTC, closed without merging

2023-11-02 13:52 UTC, koppor commented
Follow-up at https://github.com/JabRef/jabref/pull/10601.