Add support for scite.ai
JabRef/jabref pull request #10617
Opened 2023-11-03 01:31 UTC by u7500248

Closes https://github.com/koppor/jabref/issues/375

"Add support for scite.ai" - Retrieves scite.ai "Smart Citation" tallies for the selected citation (if a DOI exists)

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

![image](https://github.com/JabRef/jabref/assets/142129932/2d57b138-a696-4c9c-b986-a21d5b3d2682)

![image](https://github.com/JabRef/jabref/assets/142129932/796b5efc-f71c-49cd-94f4-6fecd88644e4)

2023-11-03 20:16 UTC, Siedlerchr commented on CHANGELOG.md
> +### Added
Remove

2023-11-03 20:18 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTab.java
> +        titleLabel.setStyle("-fx-font-size: 1.5em;-fx-font-weight: bold;");
Please move all padding and style stuff to the EntryEditor.css so it can be tweaked from the outside

2023-11-03 20:19 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTabViewModel.java
> +    public static class SciteTallyDTO {
Move this to a new class file

2023-11-03 20:21 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTab.java
> +        String url = "https://scite.ai/reports/" + URLEncoder.encode(tallyDTO.getDoi());
Make urls constants, makes it easier to adapt them if something changes

2023-11-03 20:23 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTabViewModel.java
> +            throw new RuntimeException(ex);
Please don't catch generic Exceptions catch the most specific ones. https://stackify.com/best-practices-exceptions-java/ 
And mabye retthrow this in a maybe FetcehrException?

2023-11-03 20:24 UTC, Siedlerchr requested changes
Overall goes into the right direction, just some code style issues

2023-11-06 04:29 UTC, u7500248 commented
@Siedlerchr I have made those requested changes, are you able to take another look?

2023-11-06 15:56 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTab.java
> +        messageBox.setStyle("-fx-padding: 30 0 0 30;");
Please add that as well to the css

2023-11-06 16:01 UTC, Siedlerchr requested changes

2023-11-06 16:01 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/entryeditor/SciteTabViewModel.java
> +            searchError.set("Null Entry!");
I think Null entry is not helpful for the user, maybe something like: No active entry
And please also localize the error messages 
https://devdocs.jabref.org/code-howtos/localization.html

2023-11-06 16:01 UTC, Siedlerchr commented on src/main/resources/l10n/JabRef_en.properties
> +Scite=Scite
I don't think "Scite" needs to be translated, Scite is the name of the provider/service/company

2023-11-08 02:34 UTC, u7500248 commented
@Siedlerchr Thanks for the feedback. I have made the requested changes.

2023-11-09 19:31 UTC, Siedlerchr commented
LGTM! Just applied some small refactorings and another l10n string.

2023-11-09 19:35 UTC, Siedlerchr commented
Follow up: Move all the boolean entry editor preferences for each status to an enum Map

2023-11-09 19:53 UTC, calixtus approved these changes

2023-11-09 21:53 UTC, Siedlerchr approved these changes

2023-11-10 00:23 UTC, merged