App semantic scholar api key to properties
JabRef/jabref pull request #10656
Opened 2023-11-20 20:39 UTC by Siedlerchr

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-11-21 10:00 UTC, koppor requested changes

2023-11-21 16:50 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/BuildInfo.java
> +        semanticScholarApiKey = BuildInfo.getValue(properties, "semanticScholarApiKey", "");
I don't understand the comment. The default value?

2023-11-21 16:50 UTC, Siedlerchr commented on src/test/java/org/jabref/logic/importer/fetcher/ArXivFetcherTest.java
> +                .withField(StandardField.MONTH, "#oct#")
Not relevant here I think

2023-11-22 12:48 UTC, koppor approved these changes

2023-11-22 12:59 UTC, merged