Implement scrollable warning messages in alert boxes
JabRef/jabref pull request #10700
Opened 2023-12-14 03:38 UTC by garymejia

Added a scrollbar to the "Open library error" popup window to prevent extension beyond the screen when handling large bib files with citation errors. This enhancement ensures the window remains within the screen boundaries.
Closes #10674

![WarningScroll](https://github.com/JabRef/jabref/assets/50064854/1e31a54e-99c1-43a6-99cc-1b8ecb60c2f9)

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ x] Manually tested changed features in running JabRef (always required)
- [ x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-12-16 10:27 UTC, koppor requested changes
Thank you for taking initiative! - Please ensure that you have [JabRef's code style settings in place](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html). Checkstyle complains about wrong import order.

I wonder whether there can be tests added?

At least for `getErrorMessages()` there should be a test.

Reason: This is a logic module - and one or more tests can help enhancing that core funtionality.

2023-12-16 22:24 UTC, garymejia commented
I'll work on getting a test setup soon. Let me know if I committed incorrectly. Still trying to get a hang of this haha.

2023-12-18 20:48 UTC, calixtus approved these changes

2023-12-18 20:48 UTC, koppor approved these changes

2023-12-18 20:49 UTC, koppor commented
@garymejia Thank you for the PR. We will merge it. You can add test cases as a follow-up if you want!

2023-12-18 21:00 UTC, merged