Fix HTML-reserved characters ('&', '<', etc)  not rendered correctly in entry preview
JabRef/jabref pull request #10733
Opened 2023-12-31 18:57 UTC by HoussemNasri

Fix #10677 

## Screenshots

![image](https://github.com/JabRef/jabref/assets/21198231/3bd040ce-a68e-446c-94c3-c254810e7c23)

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-01 10:08 UTC, calixtus submitted a review, later dismissed

2024-01-01 10:09 UTC, calixtus commented
Looks good so far, how about some simple tests?

2024-01-02 12:03 UTC, koppor requested changes
I have one minor feedback (also via `/review` by [Codium](https://app.codium.ai/)

> Consider using a compiled Pattern for the regex in normalizedFiled method to improve performance.

```java
private static final Pattern HTML_ENTITY_PATTERN = Pattern.compile("&(?!(?:[a-z0-9]+|#[0-9]{1,6}|#x[0-9a-fA-F]{1,6});)");

private String normalizedFiled(String inField) {
    // When we encounter a '&' we check if it starts an HTML entity then we skip it, otherwise
    // we should replace it with '&amp;' to be rendered correctly.
    return HTML_ENTITY_PATTERN.matcher(inField).replaceAll("&amp;") // Replace & with &amp; if it does not begin an HTML entity
                  .replaceAll("\\\\&", "&amp;") // Replace \& with &amp;
                  .replaceAll("[\\n]{2,}", "<p>") // Replace double line breaks with <p>
                  .replace("\n", "<br>") // Replace single line breaks with <br>
                  .replace("\\$", "&dollar;") // Replace \$ with &dollar;
                  .replaceAll("\\$([^$]*)\\$", "\\{$1\\}");
}
```

---

Two "major" things:

1. Refactor `HTMLCharsTest` to use `@ParamterizedTest`. I think, with OpenAI, this is just an exercise how to use OpenAI ^^. -- That would also allow "easy" addition of the test covering the changed functionality.
2. A comment that [Apache Common's escapeHtml4](https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/StringEscapeUtils.html#escapeHtml4(java.lang.String)) is not a smart escaping and does not handle LaTeX characters adn commands

2024-01-23 20:02 UTC, Siedlerchr approved these changes

2024-01-23 20:02 UTC, Siedlerchr commented
Thanks for the follow up!

2024-01-23 20:02 UTC, merged