Initial anonymization
JabRef/jabref pull request #10778
Opened 2024-01-13 22:56 UTC by koppor

When writing a paper, one copies BibTeX entries to the .bib file for the paper. Then, one deletes fields to make the library shorter. Maybe, one does not touch the entries at all. All in all, there will be inconsistencies in the bib file, which typically need manual investigation. (More discussion on that topic at https://github.com/JabRef/jabref/issues/160)

This PR adds the logic to check the references of a given list of BibEntries for consistency: Do the entries of the same entry type have the same fields set?

The output is a CSV file.

For a real-life publication (pseudonymized here), the output is as follows

![image](https://github.com/JabRef/jabref/assets/1366654/f64a73b7-7c3b-4d9d-b2b1-6cf33e24671a)

---

Future work is to provide an integration in the UI.

---

This PR gets reviewable if https://github.com/JabRef/jabref/pull/10776 is merged.

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-15 21:01 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/quality/consistency/PaperConsistencyCheckResultCsvWriter.java
> +                      bibEntries.forEach(Unchecked.consumer(bibEntry -> {
Refactor to own method

2024-01-15 21:02 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/quality/consistency/PaperConsistencyCheckResultCsvWriter.java
> +                                      return "x";
make this constants

2024-01-15 21:02 UTC, Siedlerchr requested changes
some refactorings necessary

2024-01-15 21:02 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/quality/consistency/PaperConsistencyCheck.java
> +                        int first = e1.getFields().size() - e2.getFields().size();
Extract this to a comparator method stuff

2024-01-16 00:09 UTC, koppor commented
Will try to add MArkdown output in this PR, too.

2024-01-27 19:30 UTC, Siedlerchr commented
Should we merge this first draft?

2024-01-27 21:12 UTC, koppor commented
> Should we merge this first draft?

Very OK for me!

There won't be markdown, but an ASCII ouput (like the one of [lychee](https://github.com/lycheeverse/lychee/)) to really enable it for usage in a CI.

2024-01-27 21:26 UTC, Siedlerchr approved these changes

2024-01-27 21:36 UTC, merged