Added tests for invalid BibTex Files
JabRef/jabref pull request #10809
Opened 2024-01-21 23:56 UTC by garymejia

Tests were added as requested from the conversation in the merged pull request #10711. The tests added aim to correctly assert when the imported file returns warnings for improper citation keys and when the imported file throws an error for improper syntax in a imported bib entry. 

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-22 14:22 UTC, koppor requested changes
Thank you for working on this. Please fix checkstyle - and use JUnit's `@TempDir`. See other code in JabRef how to use.

Could you try to remove your updates of `abbrv.jabref.org` and `csl-styles`? Maybe by merging upstream/main? Maybe, it is also possible via GitHub's UI...

2024-01-22 14:22 UTC, koppor commented on src/test/java/org/jabref/logic/importer/ParserResultTest.java
> +            if (!tempFile.delete()) {
No need to delete temp files. This is handled by JUnit. Please use `@TempDir` annotation to make use of that functionality.

2024-01-23 01:45 UTC, garymejia commented
Sorry I just realized I didn't remove my updates to abbrv.jabref.org and csl-styles. I'll try to resolve that

2024-01-23 16:42 UTC, calixtus commented
> Could you try to remove your updates of `abbrv.jabref.org` and `csl-styles`? Maybe by merging upstream/main? Maybe, it is also possible via GitHub's UI...

Had the same problem recently, did not work at all. Git wouldn't let me remove these changes, github ui is useless for this. Git submodules is a horrible thing, makes some things way easier and some things - argh!
I believe these submodule changes are ignored anyway when merging into main.

2024-01-27 04:17 UTC, garymejia commented
Sorry I'm not sure what to run to discard those modified files. I tried merging to upstream but it didn't seem to help.

2024-01-27 06:47 UTC, calixtus commented
git merge upstream/master

2024-01-27 06:53 UTC, calixtus commented
Hm, also seems that you did not create a separate branch for your changes, but did your changes in your main branch. But this should not have an effect to this. Please remember to always create a new branch you commit your changes to, otherwise you are blocked from making any other change without further complications.

2024-01-29 02:33 UTC, garymejia commented
Unfortunately merging upstream main doesnt remove the changed files from what I can see.

2024-02-03 18:29 UTC, Siedlerchr commented
I fixed the issues with the submodules in https://github.com/JabRef/jabref/pull/10852

2024-02-03 18:29 UTC, closed without merging

2024-02-03 18:30 UTC, Siedlerchr commented on src/test/java/org/jabref/logic/importer/ParserResultTest.java
> +        File tempFile = new File(tmpDir.toFile(), "invalidBibTex.bib");
I fixed this in the follow up PR but you can just do:
        Path tempFile = tmpDir.resolve("invalidBibTex.bib");