Fixed open issue "improve response when clicking on the general tab"
JabRef/jabref pull request #10820
Opened 2024-01-23 14:18 UTC by pratyushvatsalshukla

…h For Improvised Performance

### By Default Disabled Automatic Indexing Linked Files for FullText Search. It is going to improve the performance. 
UI Path : File-> Preferences -> LinkedFiles -> Automatically index all linked files for fulltext search

![Screenshot 2024-01-23 194301](https://github.com/JabRef/jabref/assets/54927584/66bba9da-5cf7-491a-a25f-832bb7b7d242)

#9800 

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-23 16:20 UTC, calixtus requested changes
Hi, thanks for your interest in JabRef and open source programming.
The change you made however does not make any sense.
Please describe your reasoning for your change and why this should improve the performance.

The comments in the issue description seem to be somewhat misleading.

2024-01-23 16:20 UTC, calixtus commented on src/main/java/org/jabref/gui/preferences/linkedfiles/LinkedFilesTabViewModel.java
> +        fulltextIndex.setValue(!filePreferences.shouldFulltextIndexLinkedFiles());
This change is wrong. It does not change the default value, it just changes the logic of how to represent the preferences in the dialog and now shows simply the opposite of the actual preferences value.
Plase note that changes to default values have to be made in JabRefPreferences.
But I believe that full text indexing is already disabled by default.

2024-01-23 16:26 UTC, calixtus commented
I have to correct myself. Fulltext indexing is enabled by default. My fault. But the review is not affected by this.
Still makes me wonder, why this would impact the ui behaviour, as indexing happens in a separate cpu task and is done after a few minutes. Would be important to test the delay after indexing is done.

2024-01-23 19:09 UTC, pratyushvatsalshukla commented
@calixtus 
Earlier, lets say i Disabled that fulltext index Checkbox manually and after my work is done, i closed the app. Now again, whenever i will open the application that Full Text Index Checkbox will be Ticked automatically.
 So each time user has to go there and untick it.
 What I did, I reversed this nature. Now after my changes, Whenever a new user will open the application, that Full Text Label Checkbox will be Disabled. And if user ticks it manually, that setting will be there until the session is closed. When user Restarts/LogIn again, then that checkbox will again be disabled.

Hope I was able to explain. Looking forward for a healthy discussion. Thanks.

2024-01-23 21:24 UTC, calixtus commented
Hi @pratyushvatsalshukla,
@ThiloteE suggested, that the default value is set to false. But you do not set the default value by negating the presentation of the actual value in the preferences in the viewmodel when setting the values for the preferences. You set it in the `defaults` map in JabRefPreferences. Thats why we called the map `defaults`

See lines 772-773 in JabRefPreferences.java:
```java
        // Create Fulltext-Index by default
        defaults.put(FULLTEXT_INDEX_LINKED_FILES, true);
```

If you just change the behaviour of the value setter in the viewmodel this would mean the following
- user opens prefs dialog
- filePreferences.shouldFulltextIndexLinkedFiles() is true
- viewModule.setValues() sets the property to !filePreferences.shouldFulltextIndexLinkedFiles() (false)
- user hits save: viewModel.storeValues() sets filePreferences.setFulltextIndexLinkedFiles to false
- user opens prefs dialog again
- filePreferences.shouldFulltextIndexLinkedFiles() is false
- viewModule.setValues() sets the property to !filePreferences.shouldFulltextIndexLinkedFiles() (true)
- user hits save: viewModel.storeValues() sets filePreferences.setFulltextIndexLinkedFiles to true
- user opens prefs dialog again
- filePreferences.shouldFulltextIndexLinkedFiles() is true
- viewModule.setValues() sets the property to !filePreferences.shouldFulltextIndexLinkedFiles() (false)
- user hits save: viewModel.storeValues() sets filePreferences.setFulltextIndexLinkedFiles to false
...

2024-01-23 21:26 UTC, calixtus commented
About disabling full text indexing by default: https://github.com/JabRef/jabref/issues/9800#issuecomment-1906943054

2024-01-23 22:48 UTC, ThiloteE commented
I suggested to disable indexing as an initial form of debugging to find the real culprit for the slow response. Koppor and Processeer confirmed it could be that, but they never provided a hard proof and benchmarks, e.g. with n number of linked files, during indexing entry editor is delayed by x seconds. Later we came up with multiple proposals how we could trigger indexing differently. You chose the mose radical (but easiest) approach and disabled it completely, while automatic indexing clearly is very convenient, albeit slow in large databases. Since most users do NOT have huge databases and a preference exists that allows to disable it, I would suggest to not disable indexing by default.

2024-01-28 16:22 UTC, Siedlerchr commented
As we discussed, this is not a solution and the issue needs more refinement. Disabling the indexer is not a solution.

2024-01-28 16:22 UTC, closed without merging