improve notification toast when saving a file #9803
JabRef/jabref pull request #10828
Opened 2024-01-29 04:09 UTC by rdsingh13

I commented Saving library because its take no time in saving library so only one notification came Library saved 
### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-29 07:37 UTC, calixtus commented
Hi, thanks for your interest in jabref and open source programming.
Is there any issue linked to this pr you are fixing? Could you elaborate a bit on this description, whats the reasoning for your change?

2024-01-29 08:52 UTC, calixtus commented
Just saw the PR title.
Please note that GitHub does not parse pr titles, only the description of your pr. So if you automatically want to link your pr to an issue, you have to write fixes or closes followed by the issue number in the description. Like this:
Closes #9803

2024-01-29 08:56 UTC, calixtus commented
After reading through your changes and the issue description:
If you want to remove code, remove it, not just comment it. To keep a history of code changes is what git is for.
Second, the issue comments indicated, that there has not been yet a decision made on how to deal with the notifications. I will put a dev call tag on this one therefor.

2024-01-29 09:25 UTC, Siedlerchr commented
Do not remove this. for lage libraries it will take some time

2024-01-29 20:29 UTC, koppor requested changes

2024-01-29 20:29 UTC, koppor commented on src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java
> -            dialogService.notify("%s...".formatted(Localization.lang("Saving library")));
This should be guarded by an if. Constant SHOW_SAVING_SIZE_LIMIT 2_000. The size should be availble from the database context.

2024-02-11 12:38 UTC, Siedlerchr approved these changes

2024-02-11 17:25 UTC, Siedlerchr approved these changes

2024-02-12 15:52 UTC, koppor approved these changes

2024-02-12 16:05 UTC, merged