Applye RemoveTestPrefix
JabRef/jabref pull request #10823
Opened 2024-01-24 15:25 UTC by koppor

Follow-up to https://github.com/JabRef/jabref/pull/10797

This applies [Remove test prefix from JUnit 5 tests](https://docs.openrewrite.org/recipes/java/testing/cleanup/removetestprefix) and fixes the issues caused by https://github.com/openrewrite/rewrite-testing-frameworks/issues/462 manually.

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-01-25 10:35 UTC, koppor commented
Only FetcherTests fail, because of CiteSeer and Grobid (and others)

2024-01-25 17:18 UTC, calixtus commented on src/test/java/org/jabref/logic/layout/format/RTFCharsTest.java
> +    void rTFCharacters() {
,,,?

2024-01-25 17:22 UTC, calixtus requested changes
one misspelled method name

2024-01-27 19:28 UTC, Siedlerchr commented
I don't like this  refactoring, Even though it's not necessary, I find it easier to have the methods with test prefixed, helps it to find them

2024-01-27 20:26 UTC, calixtus commented
I have no strong opinion here, but it should be consistent everywhere. For now we have methods with and some without the prefix.

About the argument: I think the ide should help here. In intellij test classes have a green bg. But I don't know if this is what you mean?

What's more of interest to me in this matter is: what recommendation does junit make and how do the error messages look if junit produces some.

2024-01-27 21:06 UTC, koppor commented on src/test/java/org/jabref/logic/layout/format/RTFCharsTest.java
> +    void rTFCharacters() {
Submitted https://github.com/openrewrite/rewrite-testing-frameworks/issues/473

2024-01-27 21:08 UTC, koppor commented
+1 for consistency. Therefore, I applied it.

It is also based on the experience by our friends at Moderne. Thus, I trust them --> https://docs.openrewrite.org/recipes/java/testing/cleanup/removetestprefix

2024-01-27 21:26 UTC, Siedlerchr submitted a review, later dismissed

2024-01-28 16:23 UTC, Siedlerchr commented
There is something wrong with the lobid fetcher:

Failed to map supported failure 'org.opentest4j.AssertionFailedError: expected: <Optional[Paper Title]> but was: <Optional.empty>' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@151d4a62': Cannot invoke "Object.getClass()" because "expectedValue" is null

2024-01-28 20:52 UTC, koppor commented
This PR did not touch the LOBID fetcher:

![image](https://github.com/JabRef/jabref/assets/1366654/20a6cbd7-bf9c-489b-888a-b3d8b9980c77)

2024-01-29 09:23 UTC, calixtus approved these changes

2024-01-29 09:32 UTC, merged