If user moved file, it should simply be relinked(https://github.com/J…
JabRef/jabref pull request #10913
Opened 2024-02-23 17:54 UTC by akshu-dh

If user moved file, it should simply be relinked. (https://github.com/JabRef/jabref/issues/9798). 

Files will be automatically relinked. Even if user will move files from dir to its subDir. I have created loop to recursively scan through it's dir and subDir.

- It will relinked the file present inside the e.g. test.bib
- Manually tested through UI.
- I have attached the screenshots for POC.

### Mandatory checks

- [/ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ /] Tests created for changes (if applicable)
- [x ] Manually tested changed features in running JabRef (always required)
- [ x] Screenshots added in PR description (for UI changes)
- [x ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

![image](https://github.com/JabRef/jabref/assets/141035394/68d71ae7-197e-45e2-b2c9-10286d6719c3)

2024-02-23 20:07 UTC, arvindsis11 approved these changes
files are linking properly need some refinement. we can merge this

2024-02-23 20:23 UTC, arvindsis11 approved these changes

2024-02-24 11:59 UTC, Siedlerchr commented
First there are failing test, second you have used the main branch which is always a bad idea. Always create a new branch. 
See our contribution guidelines https://devdocs.jabref.org/contributing.html#understanding-the-basics-of-code-contributions
Third, the JabRef maintainers review your code and approve it or not.

2024-02-24 19:49 UTC, koppor requested changes
Tests are missing

https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/util/io/DatabaseFileLookup.java is not used. Why?

2024-02-24 19:50 UTC, koppor commented
Note that a different group of students was assigned. It is a bad style to work on already assigned issues...

2024-02-28 22:39 UTC, koppor requested changes
Does not fix the issue. A FileWatcher needs to be installed. The file directories need to be watched! See https://stackoverflow.com/q/23452527/873282. -- Maybe, there already is a file watcher? (Maybe this is not part of the issue description, but we refine it here while thinking more of it)

I don't understand why "findAssociatedNotLinked Files" is changed. -- There should be new tests to demonstrate this?

2024-03-11 23:27 UTC, koppor commented
Closing this issue due to inactivity :zzz: 

Please ping us if you intend to resume work on this one

2024-03-11 23:27 UTC, closed without merging