Convert the "Custom API key" list to a table [#10926]
JabRef/jabref pull request #10936
Opened 2024-02-28 00:52 UTC by AbdAlRahmanGad

Fix for #10926 

https://github.com/JabRef/jabref/assets/89566409/95c13fe4-5a62-45c1-ade9-f756e4e2be5d

The only difference from the previous implementation that the user can edit the "key" even if the "use custom key" is not checked. I still didn't find an efficient way to solve it so I will wait for your feedback.

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-02-28 05:37 UTC, calixtus commented on src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java
>          }
Never use try-catch for program logic. And keep the scope of the try block always as small as possible, also the Exceptions as percise as possible. See https://github.com/HugoMatilla/Effective-JAVA-Summary?tab=readme-ov-file#9-exceptions

2024-02-28 05:39 UTC, calixtus commented
Hi, thanks for your interest in JabRef and OpenSource. I like the change to the ui, yet i have a comment about your implementation. I recommend the book Effective Java by Josh Bloch. Here is a summary that I like to use myself: https://github.com/HugoMatilla/Effective-JAVA-Summary

2024-02-28 05:48 UTC, AbdAlRahmanGad commented
@calixtus Hi, thanks for the feedback. I will check the resources you provided and modify the code.

2024-02-28 09:06 UTC, Siedlerchr commented
You could disable the field if it's not selected (e.g binding)
And regarding the exception handling, better is to use Validation

2024-02-28 13:44 UTC, calixtus commented
Shouldn't the keys be hidden behind asterisks
@JabRef/developers ?

2024-02-28 15:02 UTC, Siedlerchr commented
Yeah, maybe some kind of PasswordField or something similar can be used

2024-02-28 22:32 UTC, koppor requested changes

2024-02-28 22:32 UTC, koppor commented on src/main/java/org/jabref/gui/preferences/websearch/WebSearchTabViewModel.java
> +        }
Please disable the button if no API key (row in the table!!) is selected instead of outputting a dialog. Thus, we also save new translatations.

2024-02-29 09:42 UTC, koppor reviewed
How can I change a key? I tried to click and double click (Windows 11), but nothing happened.

The checkbox on the right should be enabled only if there is a custom key.

![image](https://github.com/JabRef/jabref/assets/1366654/513d456a-6540-40ca-8858-63114a696823)

2024-02-29 09:51 UTC, AbdAlRahmanGad commented
@koppor I made that you can't enter a key unless you enable the check. https://github.com/JabRef/jabref/pull/10936/commits/091414296778f0458ddba5f431d356ab295dbe30

Should I make it the opposite: if you enter a key then the checkbox will be enabled?

2024-02-29 10:47 UTC, koppor commented
Yeah, the opposite is great. The checkmark should automatically be set then.

Maybe no disablement of the checkbox. There seem to be two kinds of user flows 🤣🤣

On dialog close, the key should only be enabled if non empty.

2024-02-29 12:56 UTC, AbdAlRahmanGad commented
@koppor Just to make sure I understood right. 
- If a user enter a key the checkbox is enabled automatically
- if the key is empty the checkbox is disabled automatically

Also, can the user change the checkbox manually?

2024-02-29 15:58 UTC, calixtus commented
Until now it was also possible to store custom keys, even if they are not used. Would be a regression if we automatically use the key if stored or remove it, when unchecked...

2024-03-01 13:53 UTC, AbdAlRahmanGad commented
@calixtus Sorry, I saw your comment after I commited.
So, should I make the user able to edit both manually?

2024-03-01 16:25 UTC, calixtus commented
There are use cases one would want to keep the custom API stores without using it, maybe just to test something maybe.

2024-03-02 14:49 UTC, AbdAlRahmanGad commented
I think the code is ready for review now.

2024-03-03 19:23 UTC, Siedlerchr commented
From my side lgtm, just one minor addition: Can you add the note that is at the tab Citation key patterns, here as well? 

<img width="423" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/fa93394c-5b43-4e83-beea-6c172353972e">

2024-03-03 19:23 UTC, Siedlerchr approved these changes

2024-03-04 19:45 UTC, koppor approved these changes

2024-03-04 19:58 UTC, merged