Add test cases for "UnicodeToLatex" and "LatexToUnicode"
JabRef/jabref pull request #11061
Opened 2024-03-20 21:24 UTC by AbdAlRahmanGad

I added the test case mentioned in [#5547](https://github.com/JabRef/jabref/issues/5547#issuecomment-554067764) and other test cases to ensure reliability. 

The problem with the test case was that ```ı̄``` is not one character it's a combination of ```ı  +   ̄``` unlike ```ā```. What was happennig is that ```ı``` was being converted to ```\i``` and then ```  ̄ ``` was being converted to ```{\={}}``` so the result would be ```{\i{\={}}}```.

I made it that we deal with such characters that cause conflict after combining accents. They are stored in a new variable called ```UNICODE_LATEX_CONVERSION_MAP_AFTER_COMBINING_ACCENTS``` I think this will be the base to deal with such cases.

I also added some of the underdot characters as the previous implementation didn't handle them.

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-03-20 22:06 UTC, calixtus commented
Maybe this could help: https://www.unicode.org/faq/char_combmark.html

2024-03-20 23:13 UTC, koppor commented
I think, all the unicode should be normalized before conversion. Use the formatter introduced at https://github.com/JabRef/jabref/pull/11056.

2024-03-20 23:14 UTC, koppor commented on src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
> +        assertEquals("ı", formatter.format("{\\i}"));
Make a `@ParamterizedTest`. I think `@CsvSource` will work well.

2024-03-20 23:15 UTC, koppor commented
> I made it that we deal with such characters that cause conflict after combining accents.

My comment above in other words: We need to rely on the normal form NFC. Base our internal maps on that. And do not introduce some other maps.

2024-03-21 07:48 UTC, koppor requested changes
Thank you for the quick action taken. Just minor comments.

---

Future work: The part at " // Combining accents" will never be touched? One should check with "code coverage"

2024-03-21 07:48 UTC, koppor commented on src/main/java/org/jabref/logic/formatter/bibtexfields/UnicodeToLatexFormatter.java
> +        NormalizeUnicodeFormatter normalizer = new NormalizeUnicodeFormatter();
Make this a class constant: `public static final ...`.

Open the context menu, select "Refactor..." then "Introduce Field..."

![image](https://github.com/JabRef/jabref/assets/1366654/d6cf4f99-5bbd-41ae-b0f4-48bb0a2c7652)

Choose "field declaration" for initialization:

![image](https://github.com/JabRef/jabref/assets/1366654/09afbcc1-8eb5-4ef4-83f3-439d36c78aaa)

You will then have to make the variable name upper case. You can use <kbd>Alt</kbd>+<kbd>Enter</kbd> to get IntelliJ support:

![image](https://github.com/JabRef/jabref/assets/1366654/897d1571-f13c-4f38-a326-e0169d2d3405)

2024-03-21 07:48 UTC, koppor commented on src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java
> -
Please keep the empty line as separator

2024-03-21 07:48 UTC, koppor commented on src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
> +
Remove the empty line

2024-03-21 07:48 UTC, koppor commented on src/test/java/org/jabref/logic/layout/format/LatexToUnicodeFormatterTest.java
> +    void twoDifferentMacrons() {
Please add the a link to the issue. Just as JavaDoc with `<a href="...">...`

2024-03-21 21:40 UTC, koppor approved these changes

2024-03-21 22:03 UTC, merged