11021/fix/make easier re enable usercomment
JabRef/jabref pull request #11090
Opened 2024-03-24 18:22 UTC by Realmbird

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-03-24 18:34 UTC, subhramit commented
Localization tests have failed. Check wherever, during your development, you have used Strings (Sentences). 
Read more at https://devdocs.jabref.org/code-howtos/localization.html.

2024-03-24 19:02 UTC, koppor commented
@Realmbird The PR description should be based on the template: https://raw.githubusercontent.com/JabRef/jabref/main/.github/PULL_REQUEST_TEMPLATE.md. It currently misses a reference in the text to the issue. It also misses why this is a draft and what are the next steps. (Not all reviewers read the messages in gitter when reviewing this pull request)

2024-03-24 19:33 UTC, koppor commented
We should be more precise here:

## 1. Rename "Show user comments field" to "Show user-specific comment field" (no "s" at the end)

![image](https://github.com/JabRef/jabref/assets/1366654/be0365eb-8d74-418d-85aa-a4e7eb9a19e7)

Reasons:

1. It is only about the comment field of the **current** user, not any other user
2. It is the field specific for ("tied to") the user - not the general "comment" field

## 2. Rename "Hide user comments" to "Hide user-specific comment field"

![image](https://github.com/JabRef/jabref/assets/1366654/8768b4fe-d881-44d9-bec9-9d47516b560f)

Reasons: Same as for 1.

## 3. Rename "Show user comments" to "Show user-specific comment field"

![image](https://github.com/JabRef/jabref/assets/1366654/2cce7f7e-f96e-4f49-8fb2-3f64134c6a58)

Reasons: Same as above

## 4. Do NEITHER show "Show user-specific comment field" nor "Hide user-specific comment field" if user-specific comment already shown

Example for user "koppor"

![image](https://github.com/JabRef/jabref/assets/1366654/2b06f1e7-e654-414e-9e0b-136acf3e5d60)

![image](https://github.com/JabRef/jabref/assets/1366654/b16e178f-1519-4e3e-9fe5-ef2343ca98d3)

2024-03-24 20:06 UTC, Realmbird commented
@koppor Got all tests to pass and thank you to subhramit  for giving the hint it was a localization problem I just copied Hide\ user\ comments=Hide user comments and changed hide with show. Not sure how this works so where can I why they have \s before works is it to make it into keys?

2024-03-24 20:12 UTC, koppor requested changes
Please see my comments at https://github.com/JabRef/jabref/pull/11090#issuecomment-2016916456 for a refined requirements list.

2024-03-24 20:12 UTC, koppor commented on src/main/java/org/jabref/gui/entryeditor/CommentsTab.java
> +//                editors.add(userSpecificCommentField);
No commented-out code

2024-03-24 20:12 UTC, koppor commented on src/main/java/org/jabref/gui/entryeditor/CommentsTab.java
> +            Button showDefaultOwnerCommentButton = new Button(Localization.lang("Show user comments"));
This code is somehow similar to the if branch above. Can you factor out a method with parameters (e.g., the label of the button and whether the usercommentsfield should be shown)

2024-03-24 20:12 UTC, koppor commented on src/main/java/org/jabref/gui/entryeditor/CommentsTab.java
> +                entryEditorPreferences.setShowUserCommentsFields(true);
Please rename the method to `setShowUserSpecificCommentField`

2024-03-24 20:38 UTC, subhramit commented
> @koppor Got all tests to pass and thank you to @subhramit for giving the hint it was a localization problem I just copied Hide\ user\ comments=Hide user comments and changed hide with show. Not sure how this works so where can I why they have \s before works is it to make it into keys?

In general, in programming backslashes are used to denote escape characters in strings. In the localization file, they are used for special characters and spaces. Using "```\ ```" instead of directly using spaces makes it get recognized as a single key-value pair (key=value form), otherwise spaces will act as separators and make them get interpreted as multiple key-value pairs. Don't exactly remember where I read it, but anybody correct me if I'm wrong.

2024-03-24 22:00 UTC, Realmbird commented
Gonna try working on #11090 (comment)
for 4.  Do NEITHER show "Show user-specific comment field" nor "Hide user-specific comment field" if user-specific comment already shown
I am gonna spend some time trying to solve what causes the bug

2024-03-24 22:36 UTC, koppor commented
> Gonna try working on #11090 (comment) for 4. Do NEITHER show "Show user-specific comment field" nor "Hide user-specific comment field" if user-specific comment already shown I am gonna spend some time trying to solve what causes the bug

Just store 

    boolean isDefaultOwnerComment = field.equals(userSpecificCommentField);

in a method-local variable `hasDefaultOwnerComment`. Inside the loop, do:

    hasDefaultOwnerComment = hasDefaultOwnerComment || isDefaultOwnerComment ;

Before `// Show "Hide" button`, do 

```java
    // Do not show any buttons if user-specific comment field is present
    if (hasDefaultOwnerComment) {
        return;
    }
```

2024-04-08 23:47 UTC, koppor commented
@Realmbird May I ask if you could find time to continue working on this one?

2024-04-15 14:35 UTC, Realmbird commented
No I have quit been busy after spring break

2024-04-15 16:31 UTC, koppor commented
I think, only little things left. Will try to implement for myself.

2024-04-15 20:41 UTC, closed without merging