Improve arXiv Parsing (#11306)
JabRef/jabref pull request #11395
Opened 2024-06-19 12:05 UTC by narasimhareddyputta94

Fix: Improve arXiv Parsing (#11306)
Summary:
This pull request addresses the improvement of parsing arXiv entries in JabRef. The focus is on ensuring that arXiv-related fields are correctly identified and moved to the appropriate eprint fields, following consistent formatting guidelines.

Changes Made:

ArxivCleanup Class:

Added a new class ArxivCleanup to handle the cleanup logic for arXiv entries.
The class ensures that fields such as note, institution, version, and eid are parsed and moved to the appropriate eprint fields.
Implemented logic to trim any extra spaces to maintain consistent formatting.
Integration into CleanupWorker:

Modified the CleanupWorker class to include the ArxivCleanup job.
Updated the toJob method to recognize the ARXIV_CLEANUP enum and instantiate the ArxivCleanup class.
Unit Tests:

Added ArxivCleanupTest class to test the functionality of ArxivCleanup.
Verified that the cleanup logic correctly moves arXiv-related information to the eprint fields.
Ensured the tests handle cases with and without extra spaces in the field values.
Testing:

Added and executed unit tests in the ArxivCleanupTest class.
Ran tests to ensure correct functionality and formatting.
Successfully ran the tests using ./gradlew cleanTest test to validate changes in a clean environment.
Steps to Reproduce the Issue:

Create an entry with fields:
note: arXiv: 1503.05173
version: 1
institution: arxiv
eid: arXiv:1503.05173
Run cleanup entries with "Move preprint information from 'URL' and 'journal' field to the 'eprint' field".
Verify that the entry is updated correctly, moving information to the appropriate eprint fields.
Expected Behavior:

Information in the note, institution, version, and eid fields should be moved to the correct eprint* fields without extra spaces.
Actual Behavior:

The information was not correctly moved or formatted before this fix.
This pull request ensures that arXiv entries are correctly parsed and cleaned up, improving the overall data consistency in JabRef.

This fixes issue #11306.

2024-06-20 15:58 UTC, calixtus commented
Hi @narasimhareddyputta94 , thanks for your PR. Your changes look interesting. We will try to look into them the next days, currently we are a bit busy with our day jobs.
Please look at the failing tests, it seems your branch is not compiling currently. Therefor I mark it as a draft again.
Please also don't remove the section about the Mandatory checks for a PR, we have them there for the reason, that every contributor should remember that these checks have to be taken care of and kept in mind before creating a PR.

2024-06-26 13:05 UTC, koppor commented
@narasimhareddyputta94 Please work on the submodule configuration.

I tried to identify the cause, but I did not find the commit output by github:

![grafik](https://github.com/JabRef/jabref/assets/1366654/a3364ff8-bb93-4b15-ba3f-dd32e28e1930)

Please do the following:

- Ensure everything is committed
- `gitk --all&` (to start gitk to have the commit IDs ready if something goes wrong)
- `git merge upstream/main` (to merge the latest upstream changes)
- `git reset upstream/main` (to discard all commits and start a fresh commit)
- `git gui` (to craft a new commit. Do NOT commit the changes in the submodule. Try to revert these changes using "Commit" -> "Revert Changes")
- Create a new commit using `git gui` (maybe other git tooling you use)
- `git push -f` (to overwrite the changes also in this PR)

Now, this PR should show one commit without any submodule change

2024-07-27 19:36 UTC, subhramit commented on src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java
> -     * Example: "ABC+". See {@link org.jabref.logic.citationkeypattern.BracketedPatternTest#authorsAlpha()} for examples.
Why was this removed?

2024-08-04 22:00 UTC, koppor requested changes
Congratulations for the use of ChatGPT for trying to address the issue.

Do you have time to adress review comments?

It seems that half of the code changes are unrelated to the arXiv thing.

I would propose to split up this PR.  One part for fixing the reference dissue - and the other part for improving the citation key generator

2024-08-07 21:16 UTC, koppor commented
Too much noise in the code. Better start from scratch.

2024-08-07 21:16 UTC, closed without merging