Fix window decorations
JabRef/jabref pull request #11440
Opened 2024-06-30 06:04 UTC by calixtus

Fixes #10731 

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-07-01 09:45 UTC, koppor requested changes
Reading https://ux.stackexchange.com/a/125593/93436 and https://unix.stackexchange.com/q/43106/18033, I think there should be an **option** whether JabRef should remember its size. Default should be **yes** on Windows and **no** on Linux.

I am even thinking to put "no" as default on Windows, because when users have "FancyZones" installed, the Window management should be better...

2024-07-01 09:45 UTC, koppor commented on src/main/java/org/jabref/gui/JabRefGUI.java
>          preferences.setWindowMaximised(mainStage.isMaximized());
I would drop this line, too.

This should keep the fix at https://github.com/JabRef/jabref/issues/4939

2024-07-01 10:02 UTC, koppor commented
Note: The `x` values are "somehow" globally for multiple screens:

Example for

![image](https://github.com/JabRef/jabref/assets/1366654/e37fc121-0d29-472b-ae74-1fc1ac8dcfbb)

[javafx.stage.Screen@ede6e680 bounds:Rectangle2D [minX=0.0, minY=0.0, maxX=1600.0, maxY=2560.0, width=1600.0, height=2560.0] visualBounds:Rectangle2D [minX=0.0, minY=156.0, maxX=1600.0, maxY=2560.0, width=1600.0, height=2404.0] dpi:125.0 outputScale:(1.5,1.5), javafx.stage.Screen@42b22ab3 bounds:Rectangle2D [minX=5440.0, minY=96.0, maxX=6880.0, maxY=2656.0, width=1440.0, height=2560.0] visualBounds:Rectangle2D [minX=5440.0, minY=96.0, maxX=6880.0, maxY=2616.0, width=1440.0, height=2520.0] dpi:108.0 outputScale:(1.0,1.0), javafx.stage.Screen@21359912 bounds:Rectangle2D [minX=1600.0, minY=232.0, maxX=5440.0, maxY=2392.0, width=3840.0, height=2160.0] visualBounds:Rectangle2D [minX=1600.0, minY=232.0, maxX=5440.0, maxY=2352.0, width=3840.0, height=2120.0] dpi:139.0 outputScale:(1.0,1.0)]

2024-07-01 10:16 UTC, koppor commented
I enabled debug output, added more things to debug output and included also more checks for "out of bounds". Lets see, if this matches more cases.

2024-07-01 10:23 UTC, koppor commented
Note that the updated code also should keep https://github.com/JabRef/jabref/issues/5037 fixed.

I did not add some new preference to store the JabRef X and Y position depending on the screen where JabRef "lives". This can be a follow up (if users ask for it)

2024-07-01 10:29 UTC, koppor commented
We could always save the screen position if user moves the window. In case the user fixes the window position and then maximizes JabRef and then quits, the user-fixed window position is not stored.

2024-07-10 11:12 UTC, Siedlerchr commented
Related https://bugs.openjdk.org/browse/JDK-8326619

2024-08-02 12:44 UTC, koppor approved these changes

2024-08-02 12:45 UTC, koppor commented
There was no follow-up on my PR comment. I think, it is good to go as is, since it brings things forward (and unblocks https://github.com/JabRef/jabref/pull/11441).

Therefore, approved and added to the merge queue.

2024-08-02 13:05 UTC, merged