Added a method to create a new link manually #11017
JabRef/jabref pull request #11533
Opened 2024-07-25 03:05 UTC by Kunal77689

Manual File Entry Creation:
  Added a new button to the LinkedFilesEditor.fxml.
  Clicking this button displays a textbox where users can manually enter text/URLs. [#11017]

### Mandatory checks

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
![Screenshot 2024-07-25 003202](https://github.com/user-attachments/assets/0d4d4b84-0dcb-44a8-b7c0-05c574d2b43b)
![Screenshot 2024-07-25 003213](https://github.com/user-attachments/assets/b8ddef1c-0fda-4793-8812-06a9d8c76176)
![Screenshot 2024-07-25 003239](https://github.com/user-attachments/assets/eb1d3175-352e-4971-a6bc-7bb9d1fbaec9)

2024-07-25 22:21 UTC, koppor commented
@Kunal77689 Thank you for trying to work on this and providing a screenshot. I think, you should re-iterate on the requirement. I tried to unzip the requirement in https://github.com/JabRef/jabref/issues/11017#issuecomment-2251497990

2024-07-26 00:24 UTC, subhramit commented
Refer to https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html to conform to JabRef's Checkstyle.

2024-07-26 09:44 UTC, subhramit requested changes

2024-07-27 02:56 UTC, Kunal77689 commented on CHANGELOG.md
> +  Clicking this button displays a textbox where users can manually enter text/URLs. [#11017](...)
@subhramit Sure, I will. Thanks

2024-07-27 03:22 UTC, Kunal77689 commented
@koppor I have created another PR (#11539) which deals with the requirements discussed above. Should I go ahead and close this PR?

2024-07-27 10:55 UTC, koppor commented
@Kunal77689 Then I close this PR.

2024-07-27 10:55 UTC, closed without merging