Chat prompt history
JabRef/jabref pull request #11632
Opened 2024-08-15 15:00 UTC by InAnYan

Closes https://github.com/InAnYan/jabref/issues/149.

This PR gives users the ability to scroll past user messages in AI chat.

Similar to shells command history.

The algorithm looks clunky, but I tested it, and it seems to work good.

### Mandatory checks

~- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)~
~- [ ] Tests created for changes (if applicable)~
- [x] Manually tested changed features in running JabRef (always required)
~- [ ] Screenshots added in PR description (for UI changes)~
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-08-15 21:56 UTC, koppor requested changes

2024-08-15 21:56 UTC, koppor commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
> +    private final IntegerProperty currentUserMessageScroll = new SimpleIntegerProperty(-1);
Introduce a constant for `-1`: `NEW_EMPTY_NON_EXISTENT`.

Code should not contain magic numbers. With a reference to the constant ( `private static final`), it is possible to trace the constant.

This also gets rid of comment line 48.
line 49 can be kept

2024-08-15 21:56 UTC, koppor commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
> +                if (keyEvent.getCode() != KeyCode.RIGHT && keyEvent.getCode() != KeyCode.LEFT) {
Add comment abvoe

    // Cursor left/right should not stop history scrolling

2024-08-16 15:18 UTC, InAnYan commented
I wanted to make a separate component `HistoryTextField`, but it didn't go well.

I've added the constant and explanation in comments about how the history is handled

2024-08-18 08:17 UTC, koppor commented
> I wanted to make a separate component `HistoryTextField`, but it didn't go well.

Great idea!

As usual: Create a new minimal JavaFX project. Show current progress there.

My hope: As team, we can get it done - and then submit a PR to https://github.com/dlsc-software-consulting-gmbh/GemsFX.

2024-08-18 08:29 UTC, koppor requested changes
Constants should be used everywhere :) - not just in 90% of the cases 😅🤣🤣

2024-08-18 08:29 UTC, koppor commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
> +    private final IntegerProperty currentUserMessageScroll = new SimpleIntegerProperty(-1);
```suggestion
    private final IntegerProperty currentUserMessageScroll = new SimpleIntegerProperty(NEW_NON_EXISTENT_MESSAGE);
```

2024-08-18 08:29 UTC, koppor approved these changes

2024-08-18 11:50 UTC, merged