Add support biblatex extended name format
JabRef/jabref pull request #11975
Opened 2024-10-16 01:55 UTC by u7302654

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [/] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [/] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-10-16 08:09 UTC, koppor commented
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>


### Example:
- ✅ `Fixes #xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fixes https://github.com/JabRef/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fixes https://github.com/Koppor/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ❌ `Fixes [#xyz](https://github.com/JabRef/jabref/issues/xyz)` links pull-request to issue. Merging the PR will **NOT** close the Issue.

2024-10-16 08:14 UTC, koppor commented
I did not see any JavaFX component implementing a new JavaFX component for the entry editor: https://github.com/JabRef/jabref/issues/4558#issuecomment-1904127621. It is OK to focus on the logic only. It is OK, but then we need to create a follow-up issue.

@u7302654 Please fix checkstyle issues. You seem to have missed [Step 3: Set up JabRef's code style](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html).

Moreover, please add a screenshot to show that the sorting issue of the original poster is solved (https://github.com/JabRef/jabref/issues/4558#issue-394698254). If it is not solved, it is also OK, because it improves the data model, but then we cannot close the issue at all.

2024-10-16 19:40 UTC, koppor requested changes

2024-10-16 19:40 UTC, koppor commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> -        final boolean authorsContainAND = listOfNames.toUpperCase(Locale.ENGLISH).contains(" AND ");
This code was removed - therefore `org.jabref.logic.formatter.bibtexfields.NormalizeNamesFormatterTest` is failing. Please fix. 😅

2024-10-16 21:53 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +        Matcher matcher = Pattern.compile("(\\w+)\\s*=\\s*([^,]+)(?:,\\s*|$)").matcher(authorString);
Please compile the regex only once. Compiling regular expressions is an expensive operation.

2024-10-16 21:58 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +            nameParts.put(matcher.group(1).trim(), matcher.group(2).trim());
nitpick: Named groups would make this code clearer

2024-10-16 22:00 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +                i += 4;
A lot of magic values here, what do the 5 and 4 stand for here? If possible please delcare a constant that has a good name that explains the purpose of these values.

2024-10-16 22:08 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +        return Optional.of(new Author(givenName, givenNameAbbreviated, namePrefix, familyName, nameSuffix));
This comment doesn't say anything that the code doesn't say already, it is useless, please remove it.

2024-10-16 22:10 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +        while (tokenStart < original.length() && Character.isWhitespace(original.charAt(tokenStart))) {
A comment above this block however would be helpful.

2024-10-16 22:10 UTC, HoussemNasri commented on src/main/java/org/jabref/logic/importer/AuthorListParser.java
> +        }
A comment above this block however would be helpful.

2024-12-09 20:21 UTC, koppor commented
Closing this issue due to inactivity :zzz:

2024-12-09 20:21 UTC, closed without merging