Fix for issue #10418 - Added the ability to focus on the most viewed entries
JabRef/jabref pull request #12077
Opened 2024-10-24 14:11 UTC by ExrosZ

Describe the changes you have made here: 

- By enabling view tracking in the entry tab, JabRef will track how many times a user looks an an entry every hour.
- This information is stored on the user's machine in an MVStore. 

![Tracking](https://github.com/user-attachments/assets/ce537bc7-c4f5-4d82-9685-24be72b4ecb8)

- This can then be used to create a group that shows the X most popular entries in Y timeframe, so long as each entry has atleast one view. If there are less entries with views than entries requested, it will just show the entries with 1 or more views.

![ExampleAddgroup](https://github.com/user-attachments/assets/13ad75f6-4f1e-41f4-a12a-3c134f52db86)
![Working](https://github.com/user-attachments/assets/2948cb9a-f549-4e14-aecb-f04bd98e226a)

Closes https://github.com/JabRef/jabref/issues/10418

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

Issues with my implementation:

- Fails checkstyle due to using some static variables in EntryTabViewModel
- Fails respectLayeredArchitecture test because popularityGroup is being used to get an MVStore, this is the only way I could find to get it to work without causing locking issues.
- Likely needs some reworking to fix the above issues, but I'm genuinely lost.

2024-10-24 15:57 UTC, koppor requested changes

2024-10-24 15:57 UTC, koppor commented on src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java
> +            // Update this for more elegant error handling
AI generated. Pleasemwork on this

2024-10-24 15:57 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +                mvStore.commit(); // Save changes
AI comment. Delete.

2024-10-24 15:57 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +            if (currentTime - lastViewTime >= 3600000 && EntryTabViewModel.trackViewsProperty().get()) { // 3600000 milliseconds in one hour
Introduce constant

2024-10-24 15:57 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +import java.util.concurrent.locks.ReentrantLock;
what is this useful for?

2024-10-26 08:39 UTC, koppor requested changes
The architecture of the functionality should be changed: MVStore life cycle should be handled by the tab (and passed down to the group). See AIIndexer or SearchIndex how it could work. -- You also persist data across sessions: Thus, you will have a simlar functionality.

I do not know why ""%Group containing entries cited in a given TeX file" sneaked in. I did not find functionality about that.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +     */
It does more - there is a kind of if

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +            MVMap<String, Long> lastViewTimestamps = mvStore.openMap("lastViewTimestamps");
Nono - the map is a class variable - no need to open the map each time for writing. 

You need to shut down the mvstore when the tab is closed.

The the lifecycle of the AiService or search for examples.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +            if (currentTime - lastViewTime >= ONE_HOUR_IN_MILLISECONDS && EntryTabViewModel.trackViewsProperty().get()) {
The check for the property is too late - everything doesn't need to be done if the property is false.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +                mvStore.commit();
I think, the commit happens automatically.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/LibraryTab.java
> +        synchronized (mvStore) {
if the maps are opened after load, there is no need for `synchronized` (see below)

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/desktop/os/NativeDesktop.java
> +    }
Not here - please add to org.jabref.logic.util.Directories.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/groups/GroupDialog.fxml
> +                    </RadioButton>
This is another functionality. CHANGELOG only talks about view count. Did you work on another issue, too?

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/groups/GroupDialogView.java
> +        maxEntriesCombo.setItems(FXCollections.observableArrayList(10, 20, 50, 100, 999));
Please group by button, not by method. Otherwise, it is hard to read.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/preferences/entry/EntryTabViewModel.java
> +    // TODO: Change these from static variables 18/10/2024
Yes, please.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/preferences/entry/EntryTabViewModel.java
> +        timestampPreferences.setAddModificationDate(addModificationDateProperty.getValue()); }
Checkstyle...

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/preferences/entry/EntryTabViewModel.java
> +    // View analysis
Use `// region View Analyses` and at the end `// endregion`

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +    }
Do you really need to implent these? Some other groups do not implement it.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +        MVMap<String, Integer> viewCounts = mvStore.openMap("entryViewCounts");
Please try to make that a class variable. It is passed from the library tab on creation.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +    }
Remove --> use `org.jabref.model.entry.BibEntry#getId` instead.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +    }
MVStore should be passed by caller.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +    }
The factor should be stored upon group creation (I think on change of group properties, the group is re-created)

Always reading the property seems to slow down things.

2024-10-26 08:39 UTC, koppor commented on src/main/java/org/jabref/gui/preferences/entry/EntryTab.fxml
> +    <CheckBox fx:id="enableViewTracking" text="%Enable user behaviour analysis"/>
`Enable user behaviour analysis` --> wrong word - please try to use the same words "view tracking" below "popularity" is OK, but "bheavior analysis" is even more general. It should be consistent with src/main/java/org/jabref/gui/groups/GroupDialog.fxml.

2024-10-26 13:47 UTC, ExrosZ commented
Thanks for your review @koppor, I have exams coming up so i'll need to take a break from working on this for the next two-ish weeks, but im committed to getting this done :)

Sorry for all the mess, it's my first time contributing to a project like this.

2024-11-02 19:09 UTC, HoussemNasri commented on src/main/java/org/jabref/gui/LibraryTab.java
> +            if (currentTime - lastViewTime >= 3600000 && EntryTabViewModel.trackViewsProperty().get()) { // 3600000 milliseconds in one hour
You can use `java.time.Duration`.

2024-11-02 19:15 UTC, HoussemNasri commented on src/main/java/org/jabref/model/groups/PopularityGroup.java
> +     List<BibEntry> filteredEntries = new ArrayList<>();
Let's call this popularEntries for consistency.

2024-12-09 21:02 UTC, koppor commented
Closing this issue due to inactivity :zzz:

2024-12-09 21:02 UTC, closed without merging