Fix issue #11938: Tab in empty text area field should focus the next field
JabRef/jabref pull request #12081
Opened 2024-10-25 03:53 UTC by yeonissa

This PR addresses the issue where pressing the Tab key in an empty text area should focus the next field, but it wasn't behaving as expected. The code change ensures that when the TextArea is empty, pressing the Tab key moves the focus to the next form field.

Closes https://github.com/JabRef/jabref/issues/11938

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-10-25 13:22 UTC, koppor requested changes
Too much obvious code comments.

I did not see any screenshots. Thus, reviewers need to run the tool. I think I can do it these days.

2024-10-25 13:22 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +        // Call the constructor with an empty string.
Remove comment - the code says it.

You can add a WHY to the comment. Why the empty string is passed. (If you know)

2024-10-25 13:22 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +        // Add an event filter to handle key press events
Remove comment, the code says it.

2024-10-25 13:22 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +            // If the TAB key is pressed and the TextArea is empty
Remove comment, the code says it.

2024-10-25 13:22 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +                // Move the focus to the next parent element (likely the next form field)
Remove comment, the code says it.

2024-10-25 13:22 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +                // Consume the event to prevent further processing of the TAB key
Remove comment, the code says it.

2024-10-26 11:57 UTC, yeonissa commented
Hi @koppor,

Thank you for the feedback! I've now removed the obvious code comments as suggested.

2024-10-26 20:32 UTC, koppor requested changes
Did you try it out?

![image](https://github.com/user-attachments/assets/a6d83f29-4b8a-45e1-8805-825ed4b39e4d)

![image](https://github.com/user-attachments/assets/ea70bb8d-9b64-4d7d-a8c6-a146b20dee93)

Reproduce:

1. Create new library
2. Create new entry
3. Double click on entry
4. Go to "Author" field
5. Press <kbd>Tab</kbd>

2024-10-26 20:32 UTC, koppor commented
You also need to add a CHANGELOG.md entry - as soon as you really fixed the issue.

2024-10-27 11:15 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java
> +            if (event.getCode() == KeyCode.TAB && this.getText() != null && this.getText().isEmpty()) {
You can use JabRefs StringUtil.isEmpty(this.getText())

2024-12-09 20:55 UTC, closed without merging

2024-12-09 20:55 UTC, koppor commented
Closing this issue due to inactivity :zzz: 

Maybe too much AI usage here.