Show preview of the selected theme
JabRef/jabref pull request #12104
Opened 2024-10-27 05:18 UTC by NEBANU

Solves issue 10 in the JabRef Themes Repo: https://github.com/JabRef/themes.jabref.org/issues/10
It added a preview of the light and dark theme when the user selects it.
The preview is removed if the user does not change their theme or chooses a custom them.
Dark Theme Preview:
![image](https://github.com/user-attachments/assets/8d2e7173-ce2f-4da9-a673-06cdb8342b2d)
Light Theme Preview:
![image](https://github.com/user-attachments/assets/1df65211-f0a9-42da-81c8-bca7c34a8aa2)

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [X] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [X] Screenshots added in PR description (for UI changes)
- [X] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [X] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-10-27 10:30 UTC, koppor requested changes
Remove AI generated comments.

Remove image (not linked in the docs)

2024-10-27 10:30 UTC, koppor commented on CHANGELOG.md
> +- We added a preview for themes, when they are selected in preferences (to solve: https://github.com/JabRef/themes.jabref.org/issues/10)
Wrong format.

2024-10-27 13:12 UTC, Siedlerchr commented
Does not solve the original issue and does not work for custom themes, although I like the idea

2024-12-09 20:43 UTC, koppor commented
Closing this issue due to inactivity :zzz:

2024-12-09 20:43 UTC, closed without merging