Fix for koppor issue 9798
JabRef/jabref pull request #12110
Opened 2024-10-27 09:45 UTC by u7754676

This fix was co-written by [Le-Chat-BottE](https://github.com/Le-Chat-BottE) and I. We have implemented the "Automatically set file links" feature. Specifically, this was the implementation described under the heading "First Implementation" in the original issue #9798. Our implementation comes in the form of the addition of the new method **relinkFileIfMoved** in the **AutoSetFileLinks.java** file.

In addition, as requested in the issue itself, we have also created 6 new tests to test this new method, located in the **AutoSetFileLinksUtilTest.java** file. The 6 tests are as follows:

- relinkMoveFileFromRootFolderToSubfolder
- relinkMoveFileFromSubfolderToRootFolder
- relinkMoveFileFromSubfolderToSubfolder
- noRelinkCopyFileFromRootFolderToSubfolder
- noRelinkCopyFileFromSubfolderToRootFolder
- noRelinkCopyFileFromSubfolderToSubfolder

We think our code is ready for review and we welcome any feedback or suggestions. Thank you!

Fixes #9798.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-10-27 10:41 UTC, koppor requested changes
Logik is with flaws, if mutiple files are linked to an entry (e.g., coverage). It does not work.

Please improve.

2024-10-27 10:41 UTC, koppor commented on src/main/java/org/jabref/gui/externalfiles/AutoSetFileLinksUtil.java
> +        List<LinkedFile> allLinkedFiles = entry.getField(StandardField.FILE).map(FileFieldParser::parse).orElse(Collections.emptyList());
Use entry.getFiles()

2024-10-27 11:34 UTC, subhramit commented
Hey @u7754676 
The title of the PR should not contain issue numbers, as it becomes hard to follow. It should only tell what the PR is doing.

2024-12-09 20:53 UTC, koppor commented
Closing this issue due to inactivity :zzz:

2024-12-09 20:53 UTC, closed without merging