Sanitize URLs in file fields to handle invalid pipe characters ('|')
JabRef/jabref pull request #12156
Opened 2024-11-05 01:20 UTC by hitalo-siriano

Closes #11876.

- Introduced URLUtil.createUri() and URLUtil.create() to handle URL sanitization.
- Replaced direct calls to URI.create() and URI.create().toURL() with the new utility methods.
- URLs containing the pipe character ('|') are now properly encoded as '%7C' to prevent parsing errors.
- Added test cases to URLUtilTest to verify correct sanitization and URL creation.

2024-11-05 01:26 UTC, hitalo-siriano commented
Am I on the right track to resolve this Issue?

2024-11-05 17:07 UTC, HoussemNasri commented on src/main/java/org/jabref/gui/fieldeditors/URLUtil.java
> +            String urlFormat = url.replace("|", "%7C");
Please add a comment explaining why we are doing this and the relevant references.

2024-11-05 17:13 UTC, koppor reviewed
Add an Architecture Test disallowing the use of URI.create

2024-11-05 17:13 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/URLUtil.java
> +        } catch (URISyntaxException e) {
Add `@throws` JavaDoc, too

2024-11-11 21:22 UTC, koppor commented
@hitalo-siriano Are you still on it? The steps to finish it seem to be small.

2024-11-12 11:10 UTC, hitalo-siriano commented
@koppor Yes, I'm still working on the changes

2024-11-16 23:09 UTC, koppor requested changes

2024-11-16 23:09 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/URLUtil.java
no empty line between JavaDoc and method

add an empty line above JavaDoc

2024-11-16 23:10 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/URLUtil.java
> +                MalformedURLException e) {
Remove empty line (we know that the IntelliJ autoformatter creates this - but no one invested significant time to fix this)

2024-11-17 02:39 UTC, hitalo-siriano commented
@koppor I made the requested changes, is there anything else that needs to be done?

2024-11-17 07:26 UTC, koppor commented
@hitalo-siriano please see the automated output that your code misses matching our style rules. Fix that first. That reduces load on our side.

2024-11-25 21:14 UTC, koppor approved these changes

2024-11-25 21:35 UTC, merged