[OO] Improve documentation
JabRef/jabref pull request #12216
Opened 2024-11-21 10:33 UTC by subhramit

Recently I learnt about `@implNote` tags which are used to specify requirements/preconditions for methods.
This helped clean the documentation of my code a bit.

The tag shows up as "**Implementation Requirements:**" in javadoc as follows:

![Screenshot (5)](https://github.com/user-attachments/assets/c3cfb2b9-10b6-4fe3-9a65-218f83a5ca7d)

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] ~Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)~
- [ ] ~Tests created for changes (if applicable)~
- [ ] ~Manually tested changed features in running JabRef (always required)~
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-11-29 08:10 UTC, koppor requested changes

2024-11-29 08:10 UTC, koppor commented on src/test/java/org/jabref/logic/openoffice/oocsltext/CSLFormatUtilsTest.java
> +     *           3. Run this test ONLY on numeric Citation Styles.</p>
Maybe convert to Markdown (`///` instead of `*`) to have that rendered proply (Otherwise, you should use `<ol>` and `<li>`.

2024-12-03 23:37 UTC, subhramit commented
@koppor I tried to generate the javadoc using the gradle task, but it failed due to the following two errors (something related to  module export):

```
D:\git-repositories\JabRef\src\main\java\org\jabref\gui\search\GlobalSearchBar.java:68: error: package impl.org.controlsfx.skin is not visible
import impl.org.controlsfx.skin.AutoCompletePopup;
                          ^
  (package impl.org.controlsfx.skin is declared in module org.controlsfx.controls, which does not export it to module org.jabref)
```

```
D:\git-repositories\JabRef\src\main\java\org\jabref\gui\util\CustomRatingSkin.java:7: error: package impl.org.controlsfx.skin is not visible
import impl.org.controlsfx.skin.RatingSkin;
                          ^
  (package impl.org.controlsfx.skin is declared in module org.controlsfx.controls, which does not export it to module org.jabref)
```

cc: @calixtus

2024-12-04 13:41 UTC, calixtus commented
You need to modify module-info.java, but don't ask me how, it's always try and error with me, I did not yet deep dive into java module system.

2024-12-04 13:49 UTC, Siedlerchr commented
You need to add the add-export calls for the javadoc task https://github.com/JabRef/jabref/blob/0dad3e1b54fa4c90043c45b857914969a4d61d87/build.gradle#L596-L598

2024-12-17 11:02 UTC, subhramit commented
@Siedlerchr ready for merge

2024-12-17 14:14 UTC, Siedlerchr approved these changes

2024-12-17 14:31 UTC, merged