[wip] Extract Entry Editor
JabRef/jabref pull request #12210
Opened 2024-11-18 16:40 UTC by calixtus

Instead of having an instance of the EntryEditor for every LibraryTab - one is enough. One EntryEditor to rule them all, one EntryEditor to find them, one Entryeditor to bring them all and in the bottom of the interface bind them.

Wip.
Todo:
- Move Open/Close of EntryEditor to JabRefFrame
- Adapt EntryEditor to follow observables and tolerate no entry
- Adapt StateManager from DatabaseContext to LibraryTab?
-  ...

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2025-02-11 23:51 UTC, koppor commented
Related historic PRs:

- https://github.com/JabRef/jabref/pull/3187 ("Avoid recreation of the EntryEditor")
- https://github.com/JabRef/jabref/pull/2892 ("Improve performance of entry editor")

Side note: I found the PR for the maintable JavaFX migration: https://github.com/JabRef/jabref/pull/3621 (and https://github.com/JabRef/jabref/pull/3591)

2025-02-12 21:26 UTC, subhramit commented
_There can only be one._

2025-02-12 21:45 UTC, subhramit commented
Works fine for me. Although I noticed some exception logs (not related to these changes) appearing when I double click on an entry to bring up the editor after startup.
Filed an issue at https://github.com/JabRef/jabref/issues/12494

2025-02-16 16:01 UTC, Siedlerchr submitted a review, later dismissed

2025-02-16 16:19 UTC, koppor requested changes
If I close the last tab, entry editor needs to be closed, too:

![image](https://github.com/user-attachments/assets/329b5a9b-fcb7-4efc-9142-f4d83f9b893c)

---

Entry editor does not respect mode on first show

![image](https://github.com/user-attachments/assets/0c820fb9-4ce6-43b8-9be7-b4711989d22f)

Reproduce: test files of https://github.com/JabRef/jabref/pull/12510 -> open `entry-editor-tabs-bibtex.bib`

(If I open both and switch back and forth, it works)

![image](https://github.com/user-attachments/assets/c149a7e8-d0ad-4edd-9222-b9f269a8784c)

2025-03-31 20:02 UTC, koppor commented
Maybe following issue can also be fixed with this: https://github.com/JabRef/jabref/issues/12865

2025-04-03 19:13 UTC, calixtus commented
> Maybe following issue can also be fixed with this: #12865

Checked it, would require more refactoring and would overload this pr yet more.
Should be done in a later PR but should be easier with this one merged, as the scope of changes will be smaller.

2025-04-15 17:32 UTC, Siedlerchr approved these changes

2025-04-15 17:37 UTC, Siedlerchr approved these changes

2025-04-15 22:11 UTC, koppor approved these changes

2025-04-15 22:22 UTC, merged