Markdown Export Formatter
JabRef/jabref pull request #12220
Opened 2024-11-22 16:47 UTC by LinusDietz

I quickly implemented an export format in a specific (admittedly, opinionated) format to Markdown... I find the format useful to put on websites that uses Markdown as input format [website](https://linusdietz.com/publications).

For anybody who's interested, the command I use to generate the list of the website is: 
```
jabref -n -i literature.bib --exportMatches '(author="dietz"  and (entrytype=="article" or entrytype="inProceedings" or entrytype="inCollection"))',test.md,title-md
```
### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- / Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-11-22 17:22 UTC, calixtus reviewed
One suggestion about Changelog, other things look ok-ish to me.
As noone asked for this feature yet, i guess you will be the only one for a long time to use it, so opinionated implementation is fine for me.
What im not sure of is a custom SaveOrder hardcoded. Opinions?

2024-11-22 17:22 UTC, calixtus commented on CHANGELOG.md
> +- We added a Markdown export functionality [#12220](https://github.com/JabRef/jabref/pull/12220)
```suggestion
- We added a Markdown export layout [#12220](https://github.com/JabRef/jabref/pull/12220)
```

2024-11-22 20:11 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/exporter/ExporterFactory.java
> +        SelfContainedSaveOrder saveMostRecentFirst = new SelfContainedSaveOrder(SaveOrder.OrderType.SPECIFIED, List.of(new SortCriterion(StandardField.YEAR, true)));
I would simply use the save order from the preferences, just for consistency and to reduce wtfs ;)

2024-11-22 20:11 UTC, Siedlerchr approved these changes

2024-11-22 21:49 UTC, calixtus commented
Yes, preferences save order. Maybe we can make it somewhat customizable in the layout files in a follow up?

2024-11-24 05:26 UTC, calixtus requested changes
Please use prefs save order. That can and should be customizable in the future by layouts.

2024-11-25 20:48 UTC, Siedlerchr commented
You can define the export save order here:
 <img width="1120" alt="grafik" src="https://github.com/user-attachments/assets/7085596a-2297-45d5-a76f-48cfe760a9fa">

2024-11-25 20:48 UTC, Siedlerchr approved these changes

2024-11-25 20:50 UTC, LinusDietz commented
but... can you do it in the cli from e.g. a github action?

> You can define the export save order here: <img alt="grafik" width="1120" src="https://private-user-images.githubusercontent.com/320228/389697476-7085596a-2297-45d5-a76f-48cfe760a9fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NjgwODksIm5iZiI6MTczMjU2Nzc4OSwicGF0aCI6Ii8zMjAyMjgvMzg5Njk3NDc2LTcwODU1OTZhLTIyOTctNDVkNS1hNzZmLTQ4Y2ZlNzYwYTlmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQyMDQ5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTdjNGIwNDBmY2ViNTliMTgwMzgwOTFlNDg4MmZjYTQwNjAzMTdjOTMxOWZlNGVhMGY0Nzc3OTkxOGQ1MzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sAoBfVgpph3_KCrsvwLsnXP62h3c5sL0YFA_WwfAX1k">

2024-11-25 21:03 UTC, calixtus approved these changes

2024-11-25 21:04 UTC, Siedlerchr commented
Currently not possible, create a preferences file (export xml) and then you can import it via cli , "-p prefs.xml"

2024-11-25 21:26 UTC, merged

2024-11-25 22:04 UTC, koppor commented
Typically, CSL styles are used for it - and one can select "copy as text"

![image](https://github.com/user-attachments/assets/7d91686b-b83f-4b06-914b-b9032cb4539e)

Result:

```
[1]O. Kopp, C. C. Snethlage, and C. Schwentker, “JabRef: BibTeX-based literature management software,” TUGboat, vol. 44, no. 3, pp. 441–447, 2023, doi: 10.47397/tb/44-3/tb138kopp-jabref.
[2]O. Kopp, “The LaTeXtemplate generator: How micro-templates reduce template maintenance effort,” TUGboat, vol. 44, no. 2, pp. 203–207, 2023, doi: 10.47397/tb/44-2/tb137kopp-microtemplates.
[3]M. Stötzner et al., “A Systematic Technology Review of General-Purpose Open-Source TOSCA Orchestrators,” in Proceedings of the IEEE/ACM 16th International Conference on Utility and Cloud Computing, in UCC ’23. ACM, Dec. 2023. doi: 10.1145/3603166.3632130.
[4]S. König et al., “BPMN4Cars: A Car-Tailored Workflow Engine,” in 2023 IEEE 21st International Conference on Industrial Informatics (INDIN), IEEE, Jul. 2023. doi: 10.1109/indin51400.2023.10218082.
```

With some RegEx magic, this can be transformed to:

```markdown
* O. Kopp, C. C. Snethlage, and C. Schwentker, “JabRef: BibTeX-based literature management software,” TUGboat, vol. 44, no. 3, pp. 441–447, 2023, doi: 10.47397/tb/44-3/tb138kopp-jabref.
* O. Kopp, “The LaTeXtemplate generator: How micro-templates reduce template maintenance effort,” TUGboat, vol. 44, no. 2, pp. 203–207, 2023, doi: 10.47397/tb/44-2/tb137kopp-microtemplates.
* M. Stötzner et al., “A Systematic Technology Review of General-Purpose Open-Source TOSCA Orchestrators,” in Proceedings of the IEEE/ACM 16th International Conference on Utility and Cloud Computing, in UCC ’23. ACM, Dec. 2023. doi: 10.1145/3603166.3632130.
* S. König et al., “BPMN4Cars: A Car-Tailored Workflow Engine,” in 2023 IEEE 21st International Conference on Industrial Informatics (INDIN), IEEE, Jul. 2023. doi: 10.1109/indin51400.2023.10218082.
```

I know, the DOI is not linked. I filed a feature request upstream: https://github.com/michel-kraemer/citeproc-java/issues/252