Fix for IllegalArgumentException: URI is not absolute #12186
JabRef/jabref pull request #12246
Opened 2024-11-29 20:31 UTC by yash-agrawal03

This PR closes: https://github.com/JabRef/jabref/issues/12186

Added a check to ensure that the URI is absolute before converting it to a URL in the create method. This prevents the IllegalArgumentException: URI is not absolute error by throwing a MalformedURLException with a descriptive message if the URI is not absolute.

### Description

This PR addresses a bug where the `create` method would throw an `IllegalArgumentException` if the URI was not absolute.

### Changes

1. **File**: `src/main/java/org/jabref/logic/util/URLUtil.java`
   - **What**: Added a check in the `create` method to ensure that the URI is absolute before converting it to a URL.
   - **Why**: To prevent the `IllegalArgumentException: URI is not absolute` error by throwing a `MalformedURLException` with a descriptive message if the URI is not absolute.

### Detailed Explanation

1. **Added Check for Absolute URI**:
   - Before converting the URI to a URL, the code now checks if the URI is absolute. If it is not, it throws a `MalformedURLException`.

```java
public static URL create(String url) throws MalformedURLException {
    URI uri = createUri(url);
    if (!uri.isAbsolute()) {
        throw new MalformedURLException("URI is not absolute: " + url);
    }
    return uri.toURL();
}
```

This ensures that only valid absolute URIs are converted to URLs, preventing the error you encountered.

### Mandatory checks

- [x] I own the copyright of the code submitted and I licence it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-11-29 21:08 UTC, yash-agrawal03 commented
@koppor  Could you please review the PR? I have resolved the bug that was present. Regarding the failing test case, it fails even when I run the script on the main branch's code. Could you check if this is an error on your side? Thank you

2024-11-30 05:22 UTC, subhramit commented
> Regarding the failing test case, it fails even when I run the script on the main branch's code. Could you check if this is an error on your side? Thank you

Are you talking about the failing openrewrite test?

2024-11-30 05:24 UTC, yash-agrawal03 commented
Yes, I’m talking about the openrewrite test.

On Sat, 30 Nov 2024 at 10:52 AM, Subhramit Basu Bhowmick <
***@***.***> wrote:

> Regarding the failing test case, it fails even when I run the script on
> the main branch's code. Could you check if this is an error on your side?
> Thank you
>
> Are you talking about the failing openrewrite test?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JabRef/jabref/pull/12246#issuecomment-2508837732>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS7DS3XSSYKYJZC2WPW4F32DFDRTAVCNFSM6AAAAABSXWZ6MWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBYHAZTONZTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-30 05:26 UTC, subhramit commented
> Yes, I’m talking about the openrewrite test.

Did you try fixing it? Following what is written in the bot message?
Also ref. https://devdocs.jabref.org/code-howtos/faq.html#failing-openrewrite-tests

2024-11-30 05:30 UTC, yash-agrawal03 commented
I tried using the gradle rewriterun, but it just removed the library for
assert equals from the import and didn’t help me, pass the tests. Is there
any other workaround or docs to be followed?

On Sat, 30 Nov 2024 at 10:56 AM, Subhramit Basu Bhowmick <
***@***.***> wrote:

> Yes, I’m talking about the openrewrite test.
>
> Did you try fixing it? Following what is written in the bot message?
> Also ref.
> https://devdocs.jabref.org/code-howtos/faq.html#failing-openrewrite-tests
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JabRef/jabref/pull/12246#issuecomment-2508839033>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS7DS6ZTIILIYTN7CGTUPL2DFEAXAVCNFSM6AAAAABSXWZ6MWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBYHAZTSMBTGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-30 05:32 UTC, subhramit commented
> I tried using the gradle rewriterun, but it just removed the library for
> assert equals from the import and didn’t help me, pass the tests. Is there
> any other workaround or docs to be followed?
>

Use the gradle sidebar and double click on the task as shown in the link.

2024-11-30 05:43 UTC, yash-agrawal03 commented
Thank You, this worked out!

On Sat, Nov 30, 2024 at 11:02 AM Subhramit Basu Bhowmick <
***@***.***> wrote:

> I tried using the gradle rewriterun, but it just removed the library for
> assert equals from the import and didn’t help me, pass the tests. Is there
> any other workaround or docs to be followed?
>
> Use the gradle sidebar and double click on the task as shown in the link.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JabRef/jabref/pull/12246#issuecomment-2508840746>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS7DSZRANIWQ6NWTARPGH32DFEXRAVCNFSM6AAAAABSXWZ6MWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBYHA2DANZUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-30 05:51 UTC, subhramit requested changes
Please also fix the submodules committed:
https://devdocs.jabref.org/code-howtos/faq.html#submodules

2024-11-30 05:51 UTC, subhramit commented on CHANGELOG.md
> +- We Fixed an error where saving a non-absolute URI threw an IllegalArgumentException. Now, it checks if the URI is absolute and throws a clear error message if it is not.[#12186](https://github.com/
```suggestion
- On saving a non-absolute URI, now a clear error message is shown. [#12186](https://github.com/JabRef/jabref/issues/12186)
```

2024-11-30 05:51 UTC, subhramit commented on CHANGELOG.md
> +- We Fixed an error where saving a non-absolute URI threw an IllegalArgumentException. Now, it checks if the URI is absolute and throws a clear error message if it is not.[#12186](https://github.com/
Changelog is primarily for the users. This would be too long and technical for the user to understand.

2024-11-30 09:03 UTC, koppor commented
> I tried using the gradle rewriterun, 

Could you share the content of your JAVA_HOME setting?

2024-11-30 11:13 UTC, koppor requested changes
This is not a solution. JabRef should work with these "relative" URLs, too.

2024-12-02 07:58 UTC, yash-agrawal03 commented
@koppor , This update does work with "realative" urls, can you please clarify a little or give some case, which I didn't cover? Thank You

2024-12-02 08:29 UTC, koppor commented
> @koppor , This update does work with "realative" urls, can you please clarify a little or give some case, which I didn't cover? Thank You

The example of https://github.com/JabRef/jabref/issues/12186#issuecomment-2472663129 should give no error, but work. Web page can be opened etc.

2024-12-10 13:22 UTC, koppor commented
Closing this issue due to inactivity :zzz: 

Please ping us if you intend to resume work on this one.

2024-12-10 15:58 UTC, yash-agrawal03 commented
Hi Oliver, I actually want to work on the issue, just got busy with some
work, will finish it by this week.

On Tue, Dec 10, 2024 at 6:53 PM Oliver Kopp ***@***.***>
wrote:

> Closing this issue due to inactivity 💤
>
> Please ping us if you intend to resume work on this one.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JabRef/jabref/pull/12246#issuecomment-2531626199>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS7DS4UACT74RNSF4RPKSL2E3TLTAVCNFSM6AAAAABSXWZ6MWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGYZDMMJZHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-02-10 23:57 UTC, koppor commented
> Hi Oliver, I actually want to work on the issue, just got busy with some work, will finish it by this week.

I stumbled on this... I think "this week" is over?

2025-02-10 23:58 UTC, koppor commented
Closing this issue due to inactivity :zzz: 

Please ping us if you intend to resume work on this one.

2025-02-10 23:58 UTC, closed without merging