Add notice on usage of local models
JabRef/jabref pull request #12298
Opened 2024-12-16 14:05 UTC by InAnYan

![image](https://github.com/user-attachments/assets/19c227e6-b695-4338-852b-65bfa7e271fd)

Changes:

1. Rename AI provider `OpenAI` to `OpenAI (or API compatible)`.
2. When local models are used, add additional notice that JabRef is not responsible for model output.

Rationales:

1. When using a local model (by choosing "OpenAI" and changing API base URL), funny thing happen: AI chat will display: "Current model: OpenAI qwen2.5:3b", however OpenAI does not provide Qwen models.
2. For EU act on AI. Refs https://github.com/JabRef/jabref-issue-melting-pot/issues/730

### Mandatory checks

- [x] I own the copyright of the code submitted and I license it under the [MIT license](https://github.com/JabRef/jabref/blob/main/LICENSE)
~- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if change is visible to the user)~
~- [ ] Tests created for changes (if applicable)~
~- [x] Manually tested changed features in running JabRef (always required)~
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-12-18 07:06 UTC, InAnYan commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.fxml
> +                   text="%Current AI model: %0. This content is generated by an AI system. Please verify its accuracy and relevance before use."
Ha! I haven't looked at "Current model:...". But you are right. I rewrote the message a bit now, what do you think about it now?

2024-12-18 07:21 UTC, subhramit commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.fxml
> +                   text="%Current AI model: %0. This content is generated by an AI system. Please verify its accuracy and relevance before use."
Yes! This one reads good.

2024-12-18 14:04 UTC, koppor requested changes

2024-12-18 14:04 UTC, koppor commented on src/main/java/org/jabref/logic/ai/AiPreferences.java
> +    public boolean isUnsafeModelSelected() {
Rename to `isSubjectToEuAiAct`?

In all cases do NOT use negations in the method name. Use `isSafeModelSelected`.

2025-01-03 13:35 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/ai/components/aichat/AiChatComponent.java
> +            noticeVbox.getChildren().add(new Label(Localization.lang("A custom or local AI model is used, JabRef is not responsible for the content generated by the model.")));
Do we need this EU AI Act sentence really there? 
I would just really add the overall disclaimer "JabRef is not responsible for the content generated by the model."

2025-01-03 13:38 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/ai/AiPreferences.java
> +    public boolean isUnsafeModelSelected() {
https://artificialintelligenceact.eu/assessment/eu-ai-act-compliance-checker/ 
I checked distributor and answered the questions about risk environments with none

2025-01-13 09:00 UTC, InAnYan commented
![image](https://github.com/user-attachments/assets/2c5db48f-9c2c-4911-b95a-122402a304a2)
![image](https://github.com/user-attachments/assets/aa8d2e3e-62f4-4caf-ad35-8445da6febc1)
![image](https://github.com/user-attachments/assets/2dd997a1-b6ad-49dd-9d4e-b7f579c58d67)

Definitions for "place on market" and others:
![image](https://github.com/user-attachments/assets/fc471955-130d-4d7b-80f3-97ea83e458c4)

I think I'll close the PR (as not planned), as it's highly low-prio :)

2025-01-13 09:00 UTC, closed without merging