Feature/add ui for query parsing
JabRef/jabref pull request #6805
Opened 2020-08-28 14:39 UTC by DominikVoigt

This PR is a follow-up of [#6799 ](https://github.com/JabRef/jabref/pull/6799) and adds the related UI.

The added radio button enables/disables the parsing of user queries:

![image](https://user-images.githubusercontent.com/43381984/91580101-e2cb9300-e94c-11ea-81f0-5a25920b84d1.png)

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-08-28 22:52 UTC, tobiasdiez commented
Mhhh, do you think the toggle is really necessary? I would try to have the UI as minimal as possible. Are there negative side effects to always parse the query using lucene? If I've understood your other PR correctly, input like "Some long text: subtitle" is still parsed as one default field string, right?

2020-08-30 12:20 UTC, DominikVoigt commented
> Mhhh, do you think the toggle is really necessary? I would try to have the UI as minimal as possible. Are there negative side effects to always parse the query using lucene? If I've understood your other PR correctly, input like "Some long text: subtitle" is still parsed as one default field string, right?

In the case of an unknown field, currently, the fielded term will be ignored. 
Example: author:"Jab Ref" citation-count:29 will be mapped to "Jab Ref" in the author field and 
citation-count:29 will be ignored as it does not match any field.

2020-08-31 11:46 UTC, koppor commented
This refs https://github.com/koppor/jabref/issues/341.

2020-08-31 11:59 UTC, koppor commented
I would really like to see the web search behaving similar to the JabRef search:

https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#search-modes

- Display "mode": normal mode and complex mode (see the coloring of the search icon) (I hope, we did not remove this functionality. If yes, please link the PR with the discussion)
- Optional: Hover on query displays text explaining the query

2020-08-31 22:39 UTC, calixtus requested changes
Great work. Thanks! However, found one little issue.
Greetings from JabCon2020

2020-08-31 22:39 UTC, calixtus commented on src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java
> +                querySource.setStyle("-fx-background-color: rgba(240, 128, 128, 0.5);");
Pseudo-classes could be used instead of hardcoding the colors here. See gui/util/ViewModelListCellFactory

2020-09-01 17:55 UTC, merged