No sync of specialfields to keywords
JabRef/jabref pull request #6846
Opened 2020-09-02 14:37 UTC by calixtus

fixes #6621 

Proof of concept for future refactorings to reduce the calls to `JabRefPreferences.get()` and `.put()`

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-09-02 14:47 UTC, Siedlerchr approved these changes

2020-09-02 16:30 UTC, tobiasdiez requested changes
LGTM

2020-09-02 16:30 UTC, tobiasdiez commented on src/main/java/org/jabref/gui/JabRefFrame.java
> +        if (Globals.prefs.getSpecialFieldsPreferences().getSpecialFieldsEnabled()) {
get -> is

2020-09-03 10:25 UTC, Siedlerchr approved these changes

2020-09-03 10:25 UTC, Siedlerchr commented on CHANGELOG.md
> +- We changed the synchronization of SpecialFields to keywords to not to do so as default. [#6621](https://github.com/JabRef/jabref/issues/6621)
```suggestion
- Synchronization of SpecialFields to keywords is now disabled by default. [#6621](https://github.com/JabRef/jabref/issues/6621)
```

2020-09-03 10:26 UTC, merged