Jstor Fetcher
JabRef/jabref pull request #6992
Opened 2020-10-08 15:32 UTC by joethei

added Fetcher for jstor.org

Fixes #6627

- [X] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [X] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-10-08 18:24 UTC, Siedlerchr requested changes
Thanks for your contribution! That's a nice addition. It would be cool if you could check if it's possible to extend the fetcher so it's a FullTextFetcher and downloads the pdf?

2020-10-08 18:24 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java
> +                    String data = IOUtils.toString(new URL(CITE_HOST + id), Charsets.UTF_8);
Just use our UrlDownload class:
```
URLDownload download = new URLDownload(url);
String data = download.asString()
```

2020-10-08 18:24 UTC, Siedlerchr commented on src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java
> +        assertTrue(entries.contains(expected));
```suggestion
        assertEquals(Collections.singletonList(expected), entries);
```
Using assertEquals has the advantage that you can see the difference when the test fails, e.g. sometimes the bibdata changes on the publisher site.

2020-10-08 18:24 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/importer/WebFetchers.java
> +import java.util.HashSet;
Something is odd with your import order. Did you import the JabRef code style for Intellij?
https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#using-jabrefs-code-style

2020-10-09 14:41 UTC, Siedlerchr approved these changes
LGTM now. Please fix the remaining check style issues.
For external contributes we require that at least two JabRef devs do a code review before it's merged.

2020-10-12 16:08 UTC, koppor commented
Thank you for the PR and welcome to the open source world of JabRef. Maybe you already registered for [hacktoberfest](https://hacktoberfest.digitalocean.com/). This PR will definitively count towards Hacktoberfest and we are looking for more.

I will go through your code soon. Meanwhile, may I ask to fix the checktyle issues?

>  Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java:84:9: 'if' is not followed by whitespace. [WhitespaceAround]
> Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java:93:9: 'if' is not followed by whitespace. [WhitespaceAround]

I know that we seem to ignore the red crosses at pull requests, but we are working on getting them green again. Especially "checkstyle" always was taken seriously.

2020-10-12 20:37 UTC, koppor requested changes
Looks good. Some small nitpick comments. Hope, you find time to address them.

2020-10-12 20:37 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java
> +            String response = new BufferedReader(new InputStreamReader(inputStream)).lines().collect(Collectors.joining(OS.NEWLINE));
I think, the modern way is:

```suggestion
            String response = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
```

(Source: https://stackoverflow.com/a/32352386/873282)

2020-10-12 20:37 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java
> +            Document doc = Jsoup.parse(response);
Why can't you use the method directly reading from the input stream? https://jsoup.org/apidocs/org/jsoup/Jsoup.html#parse(java.io.InputStream,java.lang.String,java.lang.String)

2020-10-12 20:37 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java
> +                BibtexParser parser = new BibtexParser(importFormatPreferences, new DummyFileUpdateMonitor());
There is no need to instantiate the parser for each parse run. Please instantiate before the loop

2020-10-12 20:37 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/JstorFetcher.java
> +                    throw new ParseException("could not download data from jstor.org", e);
```suggestion
                    throw new ParseException("Could not download data from jstor.org", e);
```

2020-10-12 20:37 UTC, koppor commented on src/test/java/org/jabref/logic/importer/fetcher/JstorFetcherTest.java
> +        assertEquals(new URL("https://www.jstor.org/stable/pdf/90002164.pdf"), url.get());
One can merge these two lines

```suggestion
        assertEquals(Optional.of(new URL("https://www.jstor.org/stable/pdf/90002164.pdf")), url);
```

2020-10-12 20:40 UTC, koppor commented
One more thing - if possible - could you add org.jabref.logic.importer.fetcher.SearchBasedFetcherCapabilityTest? That would help @DominikVoigt to add support for JSTOR for his SLR addition to JabRef. - No need do it in this PR, maybe as follow up PR? #hacktoberfest

2020-10-14 09:15 UTC, koppor commented
I get 403 at a test:

```
Test supportsJournalSearch() FAILED

  org.jabref.logic.importer.FetcherException: A network error occurred while fetching from jstor.org/open/search?Query=pt%3A%22Test%22

  Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: jstor.org/open/search?Query=pt%3A%22Test%22

  Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: jstor.org/open/search?Query=pt%3A%22Test%22
```

I think, it's a permission issue. Thus, I go ahead with merging!

Thank you for the quick follow up!

2020-10-14 09:15 UTC, merged