support for exporting to YAML format.
JabRef/jabref pull request #7007
Opened 2020-10-12 14:35 UTC by joethei

- Support for exporting to YAML per #6974 
- Fixed deleteBlankLines parameter in TemplateExporter not working.
- Enabled deleteBlankLines for the RIS Exporter, which used to have that enabled.

- [x] Change in CHANGELOG.md described (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-10-12 21:00 UTC, koppor requested changes
Looks good. Some nitpicks remaining. The empty line fix should have gone in a separate PR as discussions on regular expressions typically take more time. Let's see if it goes well, here.

Could you also add a test case for the example at https://github.com/JabRef/jabref/issues/6974? I think, there could be issues at the date export. - Maybe good for a follow-jup PR?

2020-10-13 07:33 UTC, joethei commented on src/main/resources/resource/layout/yaml.layout
> +\begin{date}  issued: \date\end{date}
no that is not the shown date format, Pandoc accepts a number of different formats for dates.
Using pandoc to convert a .bib file to .yaml also outputs yyyy-mm-dd.

2020-10-13 07:48 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/exporter/TemplateExporter.java
> +                        String[] lines = layout.doLayout(entry, databaseContext.getDatabase()).split("\n");
Maybe it should check both? We don't know which line endings the user has in the template files (if modified)

2020-10-14 09:18 UTC, koppor commented on src/main/resources/resource/layout/yaml.layout
> +\begin{date}  issued: \date\end{date}
Is it possible to add the test bib from #6974 or is that difficult?

2020-10-14 09:18 UTC, koppor commented
I see the unit tests failing:

```
  Test exportCorrectContent(Path) FAILED

  org.opentest4j.AssertionFailedError: expected: <[---, references:, - id: test,   author:,   - literal: "Test Author",   title: "Test Title",   issued: 2020,   url: http://example.com, ---]> but was: <[---, references:, - id: test  author:  - literal: "Test Author"  title: "Test Title"  issued: 2020  url: http://example.com---]>
      at org.jabref.logic.exporter.YamlExporterTest.exportCorrectContent(YamlExporterTest.java:77)
```

Could you please check what's going wrong there?

2020-10-14 09:34 UTC, joethei commented
> 
> 
> I see the unit tests failing:
> 
> ```
>   Test exportCorrectContent(Path) FAILED
> 
>   org.opentest4j.AssertionFailedError: expected: <[---, references:, - id: test,   author:,   - literal: "Test Author",   title: "Test Title",   issued: 2020,   url: http://example.com, ---]> but was: <[---, references:, - id: test  author:  - literal: "Test Author"  title: "Test Title"  issued: 2020  url: http://example.com---]>
>       at org.jabref.logic.exporter.YamlExporterTest.exportCorrectContent(YamlExporterTest.java:77)
> ```
> 
> Could you please check what's going wrong there?

I already fixed that issue in my local branch, currently testing the blank line deletion.

2020-10-15 11:42 UTC, Siedlerchr approved these changes

2020-10-18 18:16 UTC, calixtus requested changes
Got three nitpicks.
Thanks for the good work so far.

2020-10-18 18:16 UTC, calixtus commented on CHANGELOG.md
> +
Checkstyle linting error. Only one white line allowed

2020-10-18 18:16 UTC, calixtus commented on src/main/java/org/jabref/logic/exporter/TemplateExporter.java
> +                            LayoutFormatterPreferences layoutPreferences, SavePreferences savePreferences, boolean deleteBlankLines) {
Can you make `boolean deleteBlankLines` an enum? `KEEP_BLANKS` or `DELETE_BLANKS` is way more intuitive as `true` and `false` at the caller side.

2020-10-18 18:16 UTC, calixtus commented on src/main/java/org/jabref/logic/exporter/TemplateExporter.java
> +     * Indicate whether this is a custom export. A custom export looks for its layout files using a normal file path, while a built-in export looks in the classpath.
Please wrap the comments after 120 characters, to keep it readable in github

2020-10-19 21:36 UTC, calixtus approved these changes
LGTM! Thank you!

2020-10-20 16:56 UTC, joethei commented on src/main/resources/resource/layout/yaml.layout
> +\begin{date}  issued: \date\end{date}
adding the exact yaml file as a test case ist not difficult, but i dont think it ist necessary as pandoc also uses yyyy-mm-dd as a default. I did a a testcase that uses all those fields.

2020-10-20 21:24 UTC, koppor requested changes
Sorry for delay. Hope, you are still in the context. I have some micro comments...

2020-10-20 21:24 UTC, koppor commented on src/main/java/org/jabref/logic/exporter/BlankLineBehaviour.java
> + this enum represents the behaviour for blank lines in {@link TemplateExporter}
Full JavaDoc 😇 

```suggestion
 * This enum represents the behaviour for blank lines in {@link TemplateExporter}
```

2020-10-20 21:24 UTC, koppor commented on src/main/java/org/jabref/logic/exporter/TemplateExporter.java
> +
Please do not add two empty lines - I wonder why checkstyle did not complain

2020-10-20 21:24 UTC, koppor commented on src/main/java/org/jabref/logic/layout/format/CSLType.java
> +                StandardEntryType.Book.getDisplayName(), "book",
A simple  switch was not possible

```java
  return switch(value) {
     case StandardEntryType.Article.getDisplayName() -> "article",
     ...
     case StandardEntryType.Conference.getDisplayName() -> "paper-conference",
     ...
     default -> "no-type";
  }
```

2020-10-22 01:13 UTC, merged

2020-10-22 01:13 UTC, koppor commented
Thank you for the patience @joethei