Removed menu entry for 'Manage external file types'
JabRef/jabref pull request #7009
Opened 2020-10-12 15:47 UTC by schrothbn

Fixes #6991 
Removed the menu entry to only have one way to access 'Manage external file types' in the Preferences Dialog

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

![screenshot-6991](https://user-images.githubusercontent.com/68321970/95766022-f8094080-0cb2-11eb-9ddc-3b51295cb79f.png)

2020-10-12 20:46 UTC, koppor requested changes
Welcome to JabRef development and welcome to #hacktoberfest.

Small nitpicks, then it is good to go from my side.

2020-10-12 20:46 UTC, koppor commented on CHANGELOG.md
> +- We removed the menu entry "Manage external file types" because it's already in 'Preferences' dialog [#6991](https://github.com/JabRef/jabref/issues/6991)
Please follow [markdown-lint](https://github.com/DavidAnson/markdownlint) - have an empty line above and below an item list - see also the style of the other entries in the file

2020-10-12 20:46 UTC, koppor commented on src/main/java/org/jabref/gui/JabRefFrame.java
> -                factory.createMenuItem(StandardActions.MANAGE_EXTERNAL_FILETYPES, new EditExternalFileTypesAction()),
Please check the GitHub actions Checkstyle output:

    Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:84:8: Unused import - org.jabref.gui.externalfiletype.EditExternalFileTypesAction. [UnusedImports]

2020-10-14 16:14 UTC, schrothbn commented
> Welcome to JabRef development and welcome to #hacktoberfest.
> 
> Small nitpicks, then it is good to go from my side.
@koppor 
Thank you very much for the nice welcome and your review.  
Sorry I completely missed the unused import. 
I think I resolved now everything you mentioned.

2020-10-17 15:52 UTC, Siedlerchr approved these changes
Thanks, looks good to me! It would also be nice if you could adjust the documentation:
https://docs.jabref.org/setup/externalfiletypes (just click on "Edit at Github")

2020-10-18 18:18 UTC, calixtus approved these changes
LGTM. Thank you!

2020-10-18 18:20 UTC, merged