Feature/add abstract field to complex search
JabRef/jabref pull request #7079
Opened 2020-11-06 20:15 UTC by DominikVoigt

This PR adds the abstract field as a fielded term for complex queries and implements it for the existing complex search fetchers that support abstract field based filtering.

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-11-06 22:03 UTC, koppor requested changes
Some small nitpick comment

2020-11-06 22:03 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/ComplexSearchQuery.java
> +        result = 31 * result + (getAbstractPhrases() != null ? getTitlePhrases().hashCode() : 0);
Why not `return Objects.hash(defaultField, getAuthors(), ...)`?

2020-11-06 22:03 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fetcher/ComplexSearchQuery.java
> +                            .append(String.join(" ", getAuthors()))
While you are on it, please switch to [StringJoiner](https://docs.oracle.com/javase/8/docs/api/java/util/StringJoiner.html)

```java
StringJoiner stringJoiner = new StringJoiner(" ");
getSingleYear().ifPresent(singleYear -> stringJoiner.append(singleYear));
...
```

2020-11-06 22:29 UTC, koppor approved these changes

2020-11-07 10:28 UTC, calixtus approved these changes
LGTM

2020-11-07 10:30 UTC, calixtus commented
Two approvals -> I think I'll merge this.
Thanks for the work. I hope you succeeded in your exams well.

2020-11-07 10:30 UTC, merged