Improve library loading UX
JabRef/jabref pull request #7119
Opened 2020-11-23 15:57 UTC by HoussemNasri

When JabRef opens a library, it opens a file, runs the database parser, and after everything is done, creates a new tab in the frame with the contents of the open database.

An improvement would be to first create a tab in the frame, display a loading animation, and after the parser has finished, display all entries (or display every entry as soon as it is parsed).

there is a bug that I couldn't fix, even after data is loaded the group pane will keep showing 0 entry, you need to navigate away from the tab and back to get the real number of entries

about applying the improvement on startup, I think having a splash screen will look better something like a blocking dialog that displays a ProgressIndicator

Implement #6417

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-11-23 18:48 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
> +        dialogService.showErrorDialogAndWait(Localization.lang("Connection error"),
It would be cook if you could pass the exception as paramter to the error dialog as well, it's just one addtional paramter

2020-11-23 18:51 UTC, Siedlerchr commented
Wohoo! Thanks for your work, I just tested it with a huge library, it's really cool and looks really nice!
Codewise lgtm as well

2020-11-23 19:34 UTC, calixtus commented
I'll take a look into it the next days, im just a bit busy this week, I hope you don't mind.
About the bug: Maybe there is some var that should be a property. I'll check that.

2020-11-23 19:52 UTC, HoussemNasri commented
> I'll take a look into it the next days, im just a bit busy this week, I hope you don't mind.

Don't worry I'm not in a hurry, take your time

2020-11-24 10:51 UTC, tobiasdiez requested changes
Thanks also from my side. Some initial suggestions:

2020-11-24 12:23 UTC, HoussemNasri commented on src/main/java/org/jabref/gui/LibraryTab.java
> +    private void trackOpenNewDatabase(LibraryTab libraryTab) {
and by this, you mean trackOpenNewDatabase(), right?

2020-11-24 13:24 UTC, HoussemNasri commented on src/main/java/org/jabref/gui/importer/actions/OpenDatabaseAction.java
> +    public Node createLoadingLayout() {
There was a bug when I close a loading tab before it finishes, the tab next to it TableView would shrink but it seems using placeholder fixed it, Thank you

2020-11-24 14:12 UTC, tobiasdiez commented on src/main/java/org/jabref/gui/LibraryTab.java
> +    private void trackOpenNewDatabase(LibraryTab libraryTab) {
yes!

2020-11-27 08:56 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/LibraryTab.java
> +        if (dataLoadingTask == null) {
This condition/if is uncessary as you either return null or the dataLoadingTask.

2020-11-27 08:57 UTC, Siedlerchr approved these changes
codewise lgtm so far

2020-11-30 18:39 UTC, Siedlerchr approved these changes

2020-12-03 15:16 UTC, DominikVoigt approved these changes
Great work!
I did not test the changes, but the code looks fine to me :)!

2020-12-03 17:28 UTC, calixtus commented
I will fix some line breaks and merge tonight. Sorry for delay.

2020-12-06 17:48 UTC, Siedlerchr approved these changes

2020-12-06 17:48 UTC, merged

2020-12-06 17:48 UTC, Siedlerchr commented
Thanks again for your contribution!