Fix for issue 6959
JabRef/jabref pull request #7151
Opened 2020-12-03 00:22 UTC by luis-valdez

Fixes #6959 implementing the method `needsSharedDatabase` in the `ActionHelper` and then binding it in the class `PullChangesFromSharedDatabase`. This solution prevents the user from clicking "Pull changes from database" if a shared database is not present.

When the DatabaseLocation is **local**:
<img width="635" alt="Screen Shot 2020-12-02 at 5 13 49 PM" src="https://user-images.githubusercontent.com/23217708/100947116-31e01180-34c2-11eb-8148-8697adc0227a.png">
 
When the DatabaseLocation is **shared**:
<img width="711" alt="Screen Shot 2020-12-02 at 5 19 30 PM" src="https://user-images.githubusercontent.com/23217708/100947288-969b6c00-34c2-11eb-804e-13a5fb0289c8.png">

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2020-12-03 07:38 UTC, Siedlerchr commented
Please have a look at the failing checkstyle check. 
Can you also please test the case when no library is open? e.g. all tabs closed?

2020-12-03 12:36 UTC, tobiasdiez requested changes
Thanks! Two minor remarks from my side, then this is good to go!

2020-12-03 12:36 UTC, tobiasdiez commented on CHANGELOG.md
> +- We added a Boolean Expression to validate if the current database location is shared, preventing an exception when Pulling Changes From Shared Database. [#6959](https://github.com/JabRef/jabref/iss
The changlog should be understandable for normal users, so please remove the "boolean expression" part.

2020-12-03 12:36 UTC, tobiasdiez commented on src/main/java/org/jabref/gui/actions/ActionHelper.java
> +                        stateManager.activeDatabaseProperty().getValue().filter(context -> context.getLocation() == DatabaseLocation.SHARED).isPresent(),
Please use `Easybind.map(stateManager.activeDatabaseProperty(), ...)` instead of `createBooleanBinding`. It's a bit more readable and shorter.

2020-12-03 20:23 UTC, tobiasdiez approved these changes
Thanks!

2020-12-03 20:24 UTC, Siedlerchr approved these changes

2020-12-03 20:32 UTC, luis-valdez commented
Thanks for letting me contribute, I'll pick up another issue

2020-12-03 20:40 UTC, Siedlerchr commented
If you could fix the remaining checkstyle errors it would be fine:
```
 Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/main/java/org/jabref/gui/actions/ActionHelper.java:9:1: Wrong order for 'javafx.beans.binding.Binding' import. [ImportOrder]

Error: eckstyle] [ERROR] /home/runner/work/jabref/jabref/src/main/java/org/jabref/gui/actions/ActionHelper.java:22:1: 'com.tobiasdiez.easybind.EasyBind' should be separated from previous imports. [ImportOrder]
> Task :checkstyleMain
```

2020-12-03 20:43 UTC, luis-valdez commented
How can I run the checkstyle test to see if everything is correct?
I tried with `./gradlew checkstyleTest` but it is not working properly

2020-12-04 08:51 UTC, merged

2020-12-04 08:51 UTC, Siedlerchr commented
Thanks again for your contribution!