Link to Github contributors in about dialog
JabRef/jabref pull request #7319
Opened 2021-01-08 15:24 UTC by stefan-kolb

Remove AUTHORS file workflow

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2021-01-08 15:43 UTC, koppor commented
Alternatives: Maintain "All Contributors" (contributing ideas, discussions, feedback): https://github.com/all-contributors/all-contributors. This is much effort and causes huge mental workload. We want to spend our energy on fixing issues and providing issue feedback.

We accept that contributors contributing something before the GitHub area (on SourceForge) are not listed explicitly after merging this PR. They are still listed in v5.1 and earlier. They can also be foudn at the link. https://github.com/JabRef/jabref/blob/3ebba86978b6f5a714b7dec988a2aed04780d84a/scripts/generate-authors.sh#L54

2021-01-08 16:01 UTC, koppor commented
While working on it, we also renamed "Developers" to "Maintainers", since @JabRef/developers are more the overall maintainers. IMHO, this is more welcoming to contributors, because they are also developers, but not maintainers of JabRef. We as maintainers are also developers.

2021-01-08 16:32 UTC, Siedlerchr commented
What about core developers and contributer?

2021-01-08 20:30 UTC, tobiasdiez commented
+ 1 for removing the authors and also for this
> use something like https://github.com/mgechev/github-contributors-list to generate file

We could put the file at `jabref.org/contributors` and link it in the about dialog (and from the main website).

2021-01-09 14:16 UTC, koppor commented
>> use something like [mgechev/github-contributors-list](https://github.com/mgechev/github-contributors-list) to generate file 

> We could put the file at `jabref.org/contributors` and link it in the about dialog (and from the main website).

Another tool is "true-contributors", which also lists issue reporters, etc. --> https://github.com/100Automations/true-github-contributors#readme. Not too bad, too, IMHO.

2021-01-09 21:44 UTC, koppor commented
Using `jabref.org/contributors` instead of https://github.com/JabRef/jabref/graphs/contributors will be part of a follow-up PR as I don't currently have the time to implement that.

2021-01-09 22:38 UTC, Siedlerchr approved these changes

2021-01-10 15:10 UTC, tobiasdiez requested changes
LGTM, one small comment, then it can be merged.

2021-01-10 15:10 UTC, tobiasdiez commented on src/main/java/org/jabref/gui/help/AboutDialogViewModel.java
> +    private final ReadOnlyStringWrapper contributors = new ReadOnlyStringWrapper();
Since it's a static string, there is no need for an observable property. You can simply set it in the fxml via `text = %JabRef...`.

2021-01-10 18:21 UTC, calixtus approved these changes
I don't really have a strong opinion on these changes.
As long as somehow the contributors who like to be known (and also those of the sourceforge-era) get credit for their work somehow, I'm fine with the changes.

2021-01-11 06:09 UTC, koppor commented
> As long as somehow the contributors who like to be known (and also those of the sourceforge-era) get credit for their work somehow, I'm fine with the changes.

I did not receive any explicit request. Thus, I would continue here and handle "exceptions" as soon as someone raises his voice.

2021-01-11 06:10 UTC, koppor approved these changes

2021-01-11 06:10 UTC, merged