fix "Alt + keyboard shortcuts do not work"
JabRef/jabref pull request #7379
Opened 2021-01-24 13:02 UTC by Fu188

- [x] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2021-01-24 14:10 UTC, Siedlerchr approved these changes
Thanks for your contribution! Looks good to me.

2021-01-25 18:07 UTC, calixtus approved these changes
The reason for the just-in-time creation of the menu is not clear to me, it was introduced in #4707 by @davidemdot , but I have found nothing in the discussion about it. Think it's okay to remove it.

2021-01-25 18:12 UTC, calixtus commented on src/main/java/org/jabref/gui/JabRefFrame.java
> +        view.getItems().clear();
```
view.getItems().add(new SeparatorMenuItem());
view.getItems().clear();
```
This seems to be totally superfluous now.

2021-01-30 22:39 UTC, calixtus requested changes
Hi @Fu188 , I tried to fix the remaining issue I mentioned quickly by myself, but it seems, that you did not grant write access to your PR branch. So please fix the remaining issue, then we can merge.
Also Changelog.md needs some conflict resolution.

2021-01-31 02:47 UTC, Fu188 commented
> Hi @Fu188 , I tried to fix the remaining issue I mentioned quickly by myself, but it seems, that you did not grant write access to your PR branch. So please fix the remaining issue, then we can merge.
> Also Changelog.md needs some conflict resolution.

I have fix the remaining issue. Thanks for your merge!

2021-01-31 09:05 UTC, calixtus commented
Now you have introduced a lot of indentation changes in JabRefFrame (https://github.com/JabRef/jabref/pull/7379/files). Please undo them.

2021-01-31 10:02 UTC, Fu188 commented
> Now you have introduced a lot of indentation changes in JabRefFrame (https://github.com/JabRef/jabref/pull/7379/files). Please undo them.

I have undo them and it's ok now.

2021-01-31 10:55 UTC, calixtus approved these changes
Looks good to me. Thanks!

2021-01-31 19:56 UTC, tobiasdiez approved these changes
LGTM! Thanks

2021-01-31 19:56 UTC, merged