Use env to determine python3 location
JabRef/jabref pull request #7447
Opened 2021-02-15 14:22 UTC by JohannLange

In general, it is recommended to use `#!/usr/bin/env python3` as the shebang instead of the hardcoded `!#/usr/bin/python3`.
See <https://stackoverflow.com/a/5709632> for more information.
Related to [JabRef-Browser-Extension #177](https://github.com/JabRef/JabRef-Browser-Extension/issues/177), especially [this comment](https://github.com/JabRef/JabRef-Browser-Extension/issues/177#issuecomment-640054939).

- [ ] Change in CHANGELOG.md described (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2021-02-15 15:19 UTC, tobiasdiez requested changes
Thanks, that's a nice improvement indeed. Could you please also change the mac version of the script https://github.com/JabRef/jabref/blob/master/buildres/mac/jabrefHost.py and add a short entry to the changelog.

2021-02-15 15:34 UTC, JohannLange commented
> Thanks, that's a nice improvement indeed. Could you please also change the mac version of the script https://github.com/JabRef/jabref/blob/master/buildres/mac/jabrefHost.py and add a short entry to the changelog.

@tobiasdiez Done! Listed the change under *Changed*, hope thats fine :)

2021-02-15 15:41 UTC, LyzardKing commented
I thought we had changed this already. Great change.
The mac version fails to run with env (it depends where python comes from, system or brew)

2021-02-15 15:46 UTC, JohannLange commented
I see, I was only able to test it on my mac with Python installed via brew.
Any way to fix it for non-brew systems?

2021-02-15 23:51 UTC, LyzardKing commented
I tried but there were too many error reports. 
I'm not sure if there's a way to do it properly

2021-02-16 08:46 UTC, tobiasdiez commented
So on mac we still should use !#/usr/bin/python3 ?

2021-02-16 08:51 UTC, LyzardKing commented
The issue was looked at here: https://github.com/JabRef/JabRef-Browser-Extension/issues/177
If it works we should leave the mac one as is

2021-02-23 09:26 UTC, JohannLange commented
I just confirmed on a brand new Mac.
Using `/usr/bin/python3` works, but `usr/bin/env python3` would require the XCode command line developer tools.
I'll revert the changes for macOS and then the PR would be ready from my side.

2021-02-23 13:45 UTC, tobiasdiez commented
Thanks, and sorry for the misleading suggestion from my side.

2021-02-23 13:45 UTC, merged