7575 fetch
JabRef/jabref pull request #7666
Opened 2021-04-24 12:51 UTC by Ali96kz

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

2021-04-24 12:54 UTC, Ali96kz commented
![](https://user-images.githubusercontent.com/15236829/115784122-5d5a8e80-a3c6-11eb-818b-99585d8040ec.png)

2021-04-24 17:24 UTC, Siedlerchr commented
Would be nice if you could adjust your PR title to  make our life as reviewer easier ( we don't have issue numbers in our head)

2021-05-01 16:17 UTC, koppor requested changes
Thank you for the fix. Two small comments, but one large one:

We aim to have JabRef's architecture clean. Thus, there should not be any logic in a view. Proposal: Add a `CompositeFetcher` similar to `org.jabref.logic.importer.fetcher.CompositeSearchFetcher`, which tries the provided fetchers one after another.

Alternatively, introduce `DoiIsbnThenSearchBasedFetcher` class, which is a wrapper around a given fetcher and tries Doi and Isbn first.

Having that class separatetly, the code can be tested independently from the gui code.

**Update** There is `org.jabref.logic.importer.CompositeIdFetcher`. Thus, just this needs to be used at Web Search.

2021-05-01 16:17 UTC, koppor commented on src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java
> +                    // Ignored, because it can be something else
We should at least log the exception.

2021-05-01 16:17 UTC, koppor commented on src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java
> +                    // Ignored, because it can be something else
We should at least log the exception

2021-09-22 20:42 UTC, closed without merging