Fix for issue 6197: Do not store downloaded file if it is already attached
JabRef/jabref pull request #7702
Opened 2021-05-04 16:10 UTC by Pikayue11

Fix [#6197](https://github.com/JabRef/jabref/issues/6197)
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, submitted a pull request to the documentation repository.

## Reproduce this issue:

1 Choose an entry, click **search full text document online** in **Lookup**

2 If it is the first time you download it, it works well. But if it is not, it will download a duplicate file with the same content, the .bib file will has two duplicate files as below

```
file    = {:banerjee2020a - A Survey on Influence Maximization in a Social Network (2).pdf:PDF;:banerjee2020a - A Survey on Influence Maximization in a Social Network (1).pdf:PDF;:banerjee2020a - A Survey on Influence Maximization in a Social Network.pdf:PDF},
```

In this issue, we want to keep the new file with different  but delete the same one. Thus, after download a new file, we need to first judge whether the file name is the duplicate form like "xxx (1)" compare to the other files in the target directory. If yes, then compare the content of these files share the  "similar" name, if the new file has the same content as one of them, then delete it and do not add it to the linked file.

## Process to fix the issue:

1 The related code is in **LinkedFileViewModel.java**, inside the function **download()**, because we suppose that the file has already been download, the code should be inside **downloadTask.onSuccess**

2 We define a boolean function **isDuplicatedFile** in **FileNameUniqueness.java** to judge whether the file is a duplicated one in content, if yes, the newly downloaded file will be deleted and it will not be added to the linked file.

3 In **FileNameUniqueness.java** we also define function named **eraseDuplicateMarks** to change the file name like "xxx (1)" to "xxx", and return the same string if it is not in the form of duplicate file name

4 In the boolean function **isDuplicatedFile**, it will first judge whether there are other files have "similar" name with its. If  do not have, return false, indicating not duplicate. If have, compare (use **com.google.common.io.Files.equal**) the content of the newly downloaded file with all the files has "similar" file name, if the content is different from all of them, return false. If one of them has the same content with the new file's content, delete the new file,  display warning message and return true to indicate duplication happens.

## **Screenshot of the result**

#### 

Use the following .bib file for test

```
@article{banerjee2020a,
	title="A survey on influence maximization in a social network",
	author="Suman {Banerjee} and Mamata {Jenamani} and Dilip Kumar {Pratihar}",
	journal="Knowledge and Information Systems",
	volume="62",
	number="9",
	pages="3417--3455",
	notes="Sourced from Microsoft Academic - https://academic.microsoft.com/paper/3013137889",
	year="2020"
}
```

### **Before**

After **search full text document online** for three times

![test4_files](https://user-images.githubusercontent.com/73102892/117033348-da75f400-ad34-11eb-9c12-4e73fca2f671.png)

```
file    = {:banerjee2020a - A Survey on Influence Maximization in a Social Network (2).pdf:PDF;:banerjee2020a - A Survey on Influence Maximization in a Social Network (1).pdf:PDF;:banerjee2020a - A Survey on Influence Maximization in a Social Network.pdf:PDF},
```

### After
### Test1

After **search full text document online** for three times

![test5_files](https://user-images.githubusercontent.com/73102892/117033557-101add00-ad35-11eb-8af0-5c03871ff447.png)

![delete_message](https://user-images.githubusercontent.com/73102892/117033667-2c1e7e80-ad35-11eb-8ae5-02d6c8899679.png)

```
file    = {:banerjee2020a - A Survey on Influence Maximization in a Social Network.pdf:PDF},
```

### Test2
After test1, in order to test whether it will compare the content of the file, we **replace** the downloaded pdf file "banerjee2020a - A Survey on Influence Maximization in a Social Network.pdf"  with a new pdf file (we ) but keep a same name in the same folder, and then  **search full text document online** 

### The new file:

![replace_file](https://user-images.githubusercontent.com/73102892/117034097-8ddee880-ad35-11eb-93c7-33d1d8c2e0bd.png)

### The outcome:

![replace_message](https://user-images.githubusercontent.com/73102892/117033863-5ff9a400-ad35-11eb-9d91-99835515109f.png)

![replace_download](https://user-images.githubusercontent.com/73102892/117034161-9afbd780-ad35-11eb-9120-a0dcbb7defe2.png)

```
file    = {:banerjee2020a - A Survey on Influence Maximization in a Social Network (1).pdf:PDF;:banerjee2020a - A Survey on Influence Maximization in a Social Network.pdf:PDF},
```

2021-05-04 19:06 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            if (com.google.common.io.Files.equal(originalFile, duplicateFile)) {
Here then path.toFile()

2021-05-04 19:06 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            originalFile = new File(directory, originalFileName);
Paths.of...

2021-05-04 19:06 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            if (!originalFile.exists()) {
Files.exists(...)

2021-05-04 19:08 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +    public static String eraseDuplicateMarks(String fileName) {
can be private?

2021-05-05 02:51 UTC, Pikayue11 commented
Thanks for your feedback! I am a little busy today but I will improve my code as soon as possible.

2021-05-06 04:57 UTC, Pikayue11 commented
I modify my code and manually test it in running JabRef again, it works. But I delete the test cases because the method "eraseDuplicateMarks" in  "FileNameUniqueness.java" is now private

2021-05-06 15:55 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +    public static String eraseDuplicateMarks(String fileName) {
Changed to ptivate

2021-05-06 15:58 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            if (!originalFile.exists()) {
Changed to File.exists()

2021-05-06 15:58 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            originalFile = new File(directory, originalFileName);
Changed to Path.of

2021-05-06 15:59 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            if (com.google.common.io.Files.equal(originalFile, duplicateFile)) {
Changed to path.toFile()

2021-05-06 15:59 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        assert (duplicateFile.exists());
Deleted

2021-05-06 16:00 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        File duplicateFile = new File(directory, fileName);
Changed to Path.of()

2021-05-06 16:00 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        if (!originalFile.exists()) {
Changed to Files.exists()

2021-05-06 16:00 UTC, Pikayue11 commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        File originalFile = new File(directory, originalFileName);
Changed to Path.of

2021-05-06 16:16 UTC, Pikayue11 commented
I think my latest commit has solved all the problems in the recommendations. I am not very familiar with the pull request operate in github, and I just clicked all the "resolve conversation" buttons, is that matter? Besides, is there any other recommendations for my current pr? Any feedback will be appreiated. @Siedlerchr

2021-05-06 17:26 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +                    e.printStackTrace();
Use LOGGER.error(...)

2021-05-06 20:35 UTC, koppor requested changes
Thank you for working on this.

I went through the whole code. The general way of the implementation is OK (I thought about changing `FileDownloader`, but this is too early -> the file really needs to be downloaded).

I have some detailed comments. Please add test cases `eraseDuplicateMarks` and `isDuplicatedFile` need to be covered by test cases

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        Path originalFile = Path.of(directory.toString(), originalFileName);
Please use the Path API to construct file names contained in a `Path`

```suggestion
        Path originalFile = directory.resolve(originalFileName);
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        }
Please use the available methods in `FileUtil` and the power of Java optionals

```suggestion
        String fileNameWithoutDuplicated = eraseDuplicateMarks(FileUtil.getBaseName(fileName));
        String extensionSuffix = FileUtil.getFileExtension(fileName).getOrElse("");
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +                    dialogService.notify(Localization.lang("Dupilcate file with '%0', successfully delete the file '%1'", originalFileName, fileName));
```suggestion
                    dialogService.notify(Localization.lang("File '%1' is a duplicate of '%0'. Keeping '%0'", originalFileName, fileName));
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +                    dialogService.notify(Localization.lang("Dupilcate file with '%0', fail to delete the file '%1'", originalFileName, fileName));
```suggestion
                    dialogService.notify(Localization.lang("File '%1' is a duplicate of '%0'. Keeping both due to deletion error", originalFileName, fileName));
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        return fileName;
Please replace the whole method body and use regular expressions.

Hint: `(.*) \(\d+\)` and https://stackoverflow.com/q/988655/873282

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +     *
```suggestion
     *
     * This is the opposite function of getNonOverWritingFileName
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +                dialogService.notify(Localization.lang("Duplicate file name but different content, keep the new file '%0'", fileName));
I would remove this line, because the file name is not duplicate (but only simlar - hard to explain to the user)

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        while (true) {
while `true` is not a good style. This is 1990s code style with gotos.  See https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf for details.

```suggestion
        while (Files.exists(directory.resolve(originalFileName))) {
```

2021-05-06 20:35 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +            }
This can be removed, because we fixed the loop condition

```suggestion
```

2021-05-07 03:04 UTC, Pikayue11 commented
Thanks for the reply! I will fix my codes as soon as possible.

2021-05-07 19:27 UTC, koppor requested changes
Thank you for the quick reaction. Some small comments remain 😇

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +                    isDuplicate = FileNameUniqueness.isDuplicatedFile(targetDirectory.get(), destination.getFileName().toString(), dialogService);
Please use `String` only as last resort. There should always "real" domain objects be used.

```suggestion
                    isDuplicate = FileNameUniqueness.isDuplicatedFile(targetDirectory.get(), destination.getFileName(), dialogService);
```

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +                    LOGGER.error(e.toString());
Never use `toString()` to log an exception

```suggestion
                    LOGGER.error("FileNameUniquess.isDuplicatedFile failed", e);
```

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +                    entry.addLinkedFile(entry, linkedFile, newLinkedFile, linkedFiles);
Yeah!

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +     *
Please add some method description. Even if it's only one sentence

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +     * @return true when the content of files is duplicate and successfully delete the newly downloaded file ,
```suggestion
     * @return true when the content of files is duplicate and successfully delete the newly downloaded file,
```

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +    public static boolean isDuplicatedFile(Path directory, String fileName, DialogService dialogService) throws IOException {
```suggestion
    public static boolean isDuplicatedFile(Path directory, Path fileName, DialogService dialogService) throws IOException {
```

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        String fileNameWithoutDuplicated = eraseDuplicateMarks(FileUtil.getBaseName(fileName));
Introduce FileUtil.getBaseName(Path) similar to `getFileExtension(Path file) {`.

2021-05-07 19:27 UTC, koppor commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +
Add some non-null checks - the method won't work if any parameter is null:

```suggestion

        Objects.requireNonNull(directory);
        Objects.requireNonNull(filename);
        Objects.requireNonNull(diaglogService);
```

2021-05-08 06:46 UTC, Pikayue11 commented
I add an overload function getBaseName in FileUtil, imitating the code style of the function getFileExtension in FileUtil, to pass the Path variable as parameter

2021-05-11 15:35 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/util/io/FileNameUniqueness.java
> +        Pattern p = Pattern.compile("(.*) \\(\\d+\\)");
move this Pattern.compile to a static field in the class e.g. private static final Pattern DUPLICATE_MARK_PATTERN = Pattern.compile . The rest is good so far

2021-05-11 15:35 UTC, Siedlerchr approved these changes
From my side looks good so far 👍 
Just one minor improvement.

2021-05-13 05:22 UTC, Pikayue11 commented
@koppor Any other comments to improve my pr? Any feedback is appreciated.

2021-05-13 13:00 UTC, Siedlerchr approved these changes

2021-05-17 20:41 UTC, koppor approved these changes

2021-05-17 20:42 UTC, koppor commented
Thank you for keep working on this. Puts a smile on my face and a nice present for me at my free time hobby project JabRef.

2021-05-17 20:42 UTC, merged