Added more unit tests in AuthorTest
JabRef/jabref pull request #8214
Opened 2021-11-06 21:28 UTC by faco400

This adds more unit tests to the AuthorTest.java file in by applying knowledge acquired through the Software Testing discipline of the University of Brasília

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x ] Tests created for changes (if applicable)
- [x ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2021-11-07 20:24 UTC, Siedlerchr commented
It would be cool if you take the opportunity to refactor this to a parameterized unit test. https://www.baeldung.com/parameterized-tests-junit-5

2021-11-08 15:03 UTC, Siedlerchr requested changes
Please refactor to a parameterized unit test

2021-11-13 11:39 UTC, Siedlerchr approved these changes
Thanks!

2021-11-13 11:39 UTC, koppor approved these changes

2021-11-13 11:39 UTC, merged