Tinylog
JabRef/jabref pull request #8226
Opened 2021-11-08 20:25 UTC by koppor

Fixes #8007
Fixes #5475 

Debug log level is only possible with java property `-Dtinylog.level=debug `
Tiny log freezes the config after loading

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2021-12-04 15:37 UTC, Siedlerchr commented
Does not yet work https://github.com/tinylog-org/tinylog/issues/223

2021-12-18 18:26 UTC, tobiasdiez requested changes
Nice!

2021-12-18 18:26 UTC, tobiasdiez commented on CHANGELOG.md
> +- We improved the startup time from JabRef by switching from the logging library `log4j2` to `tinylog` [#8007](https://github.com/JabRef/jabref/issues/8007)
```suggestion
- We improved the startup time of JabRef by switching from the logging library `log4j2` to `tinylog` [#8007](https://github.com/JabRef/jabref/issues/8007)
```

2021-12-18 18:26 UTC, tobiasdiez commented on CHANGELOG.md
> +- We fixed an issue where Status-Logger error messages appeared on startup of JabRef [#5475](https://github.com/JabRef/jabref/issues/5475)
```suggestion
- We fixed an issue where Status-Logger error messages appeared during the startup of JabRef [#5475](https://github.com/JabRef/jabref/issues/5475)
```

2021-12-18 18:26 UTC, tobiasdiez commented on src/main/java/module-info.java
> +    requires applicationinsights.logging.log4j2;
move these things up to the "Logging" section

2021-12-18 19:00 UTC, k3KAW8Pnf7mkmdSMPHz27 approved these changes
LGTM

2021-12-18 19:05 UTC, merged