Fix for issue 8192
JabRef/jabref pull request #8229
Opened 2021-11-09 02:18 UTC by sponbob-pat

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

I saw the [frombooleans](https://github.com/JabRef/jabref/blob/3a44c6957f6c66427645c7891dee6be92067cdb9/src/main/java/org/jabref/model/metadata/SaveOrderConfig.java) method.

'frombooleans' method has 2 parameters.
First parameter needs to be given 'boolean SpecifiedOrder'.
Second parameter needs to be given 'boolean TableOrder'.

Second parameter of previous code was given 'boolean OrigianlOrder'.

So I changed that part.

Fixes [#8192](https://github.com/JabRef/jabref/issues/8198#issue-1038849241)

2021-11-10 07:31 UTC, sponbob-pat commented
"Update SaveOrderConfig.java" is about [#8133](https://github.com/JabRef/jabref/issues/8133)

Kopper's comment about WARN in #8133 gave me a clue.
(WARN org.jabref.model.metadata.SaveOrderConfig - Could not parse sort order: specified - trying to parse the sort criteria)

OrderType enum has three things. SPECIFIED, ORIGINAL, TABLE.
Therefore, correct parameter of 'valueof' function is not 'specified', 'original', 'table' but 'SPECIFIED', 'ORIGINAL', 'TABLE'.

So I attach 'toUpperCase' method to parameter of valueof function.

2021-11-10 21:47 UTC, koppor approved these changes

2021-11-10 22:26 UTC, sponbob-pat commented
Sorry, it's my mistake. :(

2021-11-12 00:59 UTC, calixtus commented
Now the preferences variable 'EXPORT_IN_ORIGINAL_ORDER` is ignored.
Please do not create a new preferences variable without need, but fix the wrong logic, otherwise we would also have to introduce preferences migrations.
So what the fromBooleans method should really look like is this:
```
        public static OrderType fromBooleans(boolean saveInSpecifiedOrder, boolean saveInOriginalOrder) {
            SaveOrderConfig.OrderType orderType = OrderType.TABLE;
            if (saveInSpecifiedOrder) {
                orderType = OrderType.SPECIFIED;
            } else if (saveInOriginalOrder) {
                orderType = OrderType.ORIGINAL;
            }

            return orderType;
        }
```

Also: the default values need to be changed in the `defaults`-map in `JabRefPreferences`, not by altering logic.

toUppercase may sound right, although i thought that valueof is case insensitive...

2021-11-12 01:00 UTC, calixtus requested changes
please adress my remarks.

2021-11-13 14:07 UTC, sponbob-pat commented
@calixtus  

If 'fromBoolean' method is defined as your suggestion, 

I think that default value of EXPORT_IN_ORIGINAL_ORDER set 'TRUE' according to your comment.
So I suggest changing as below in [JabRefPreferences.java](https://github.com/JabRef/jabref/blob/d80eb7c81888434fb7dbcb1fdd909ba4dc3bdaf8/src/main/java/org/jabref/preferences/JabRefPreferences.java)

``` java
// export order
// defaults.put(EXPORT_IN_ORIGINAL_ORDER, Boolean.FALSE);
defaults.put(EXPORT_IN_ORIGINAL_ORDER, Boolean.TRUE); 
defaults.put(EXPORT_IN_SPECIFIED_ORDER, Boolean.FALSE);
```
Because default value of EXPORT_IN_ORIGINAL_ORDER and EXPORT_IN_SPECIFIED_ORDER is all 'FALSE', 
Default save order is 'Use current table sort order' 

Is it okay?

2021-11-13 19:23 UTC, calixtus commented
Yes, that sound right. Thanks.
Go ahead, push a commit and we'll look into it.

2021-11-14 01:45 UTC, sponbob-pat commented
@calixtus I did it!

2021-11-14 08:56 UTC, calixtus approved these changes
Looks good to me! Thanks. Looking forward to see more PRs. 😄

2021-11-14 09:24 UTC, Siedlerchr approved these changes

2021-11-14 09:24 UTC, merged

2021-11-14 11:45 UTC, sponbob-pat commented
Thanks for accepting my PR!!