Clicking a DOI link in the preview pane opens web browser
JabRef/jabref pull request #8255
Opened 2021-11-16 23:54 UTC by evanpickett

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2021-11-17 20:12 UTC, calixtus commented
Hi, thanks for your PR. You can use `JabRefDesktop::openBrowser` to open a url instead of directly using awt-methods.
I think openBrowser uses awt in the end too, but it's at least a common method which behaviour can be changed eventually.

2021-11-18 20:45 UTC, evanpickett commented
> Hi, thanks for your PR. You can use `JabRefDesktop::openBrowser` to open a url instead of directly using awt-methods. I think openBrowser uses awt in the end too, but it's at least a common method which behaviour can be changed eventually.

Got it, I went ahead and re-added that functionality then

2021-11-19 06:48 UTC, calixtus commented
Great, thanks. Looks good to me! Looking forward. To see more from you eventually!

2021-11-19 06:48 UTC, calixtus approved these changes

2021-11-19 06:50 UTC, calixtus requested changes
Just overlooked an issue. Sorry. 😬

2021-11-19 06:50 UTC, calixtus commented on src/main/java/org/jabref/gui/preview/PreviewViewer.java
> +                        exception.printStackTrace();
Please use the logger instead.

2021-11-20 17:47 UTC, Siedlerchr commented
@evanpickett  Would be cool if you could fix the little remaining issue, just use LOGGER.error() so we can merge this

2021-11-20 19:27 UTC, evanpickett commented
Sorry I didn't respond quicker, let me know if you need any more changes

2021-11-20 20:33 UTC, Siedlerchr approved these changes
Thanks for the fast follow up. Just wanted to get this in! 😉

2021-11-20 20:33 UTC, merged

2021-11-25 15:40 UTC, mlep commented
Fixed in JabRef 5.4--2021-11-25--7aaf5e2
Thank you @evanpickett

2021-11-26 14:40 UTC, ThiloteE commented
hey, i just checked out the new development version and it seems this fix not only removed the functionality from entry preview, but also from the main table. Was it desired to remove this as well? Prior to this, i could double click on DOI or URL there and it would open my browser. It was quite convenient, but if this leads to uncaught exceptions...

JabRef 5.4--2021-11-25--7ec4c7e
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1