Add more tests for FieldChange Class
JabRef/jabref pull request #8614
Opened 2022-03-27 22:54 UTC by CarlosZoft

## Description :

Testing using self equals method of class FieldChange

- [x] Adding new tests

2022-03-28 19:17 UTC, koppor requested changes
Please replace `assertTrue` and `assertFalse` semantically (!) by `assertEquals`. I provided an example below.

2022-03-28 20:17 UTC, CarlosZoft commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
okayy

2022-03-28 20:40 UTC, CarlosZoft commented
Thanks for review, I think the visualization is better now.

2022-03-28 20:49 UTC, CarlosZoft commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
in this case, the objective was testing equals method of class FieldChange (override)

2022-03-28 20:51 UTC, Siedlerchr commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
Yes, but assertEquals already calls the equal method of the underlying class

2022-03-28 21:02 UTC, CarlosZoft commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
ohh I didn't know

2022-03-28 21:02 UTC, CarlosZoft commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
I will improve it, thanks

2022-03-28 21:04 UTC, Siedlerchr commented on src/test/java/org/jabref/model/FieldChangeTest.java
> +        assertTrue(fc.equals(fcBlankNewValue));
See aso the doc https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertEquals-java.lang.Object-java.lang.Object-

2022-03-28 22:28 UTC, koppor approved these changes
Even though the CI shows failing unit tests, the failing tests are not related to these changes.

2022-03-31 21:11 UTC, merged

2022-03-31 21:12 UTC, calixtus commented
Thanks for your addition to our test suite. Are you interested in working on JabRef more? We would be happy to answer your questions in our gitter channel, if you like.