Fix AuthorListParser#parse for two authors with comma
JabRef/jabref pull request #8694
Opened 2022-04-18 22:45 UTC by koppor

While reading https://github.com/JabRef/jabref/issues/8652, I found that ebook.de returns an "OKish" BibTeX:

https://www.ebook.de/de/tools/isbn2bibtex?isbn=9783110702125

```bibtex
@book{9783110702125,
  Author = {Hans-Joachim Habermann, Frank Leymann},
  Title = {Repository},
  Publisher = {Gruyter, Walter de GmbH},
  Year = {2020},
  Date = {2020-10-12},
  PageTotal = {294 Seiten},
  EAN = {9783110702125},
  URL = {https://www.ebook.de/de/product/41373251/hans_joachim_habermann_frank_leymann_repository.html}
}
```

We convert that to "good" BibTeX by using https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/importer/AuthorListParser.java. This code, however, did not work in the special case of two authors. I added a new heuristics for that case and added more test cases for that.

In the concrete case, `{Hans-Joachim Habermann, Frank Leymann}` needs to be converted to `{Habermann, Hans-Joachim AND Leymann, Frank}`

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-04-19 19:56 UTC, Siedlerchr approved these changes

2022-04-19 19:57 UTC, Siedlerchr requested changes
org.jabref.model.entry.AuthorListTest

  Test correctNamesWithOneComma() FAILED

2022-05-06 14:39 UTC, calixtus commented on CHANGELOG.md
> +- We fixe dan issue where the ISBN fetcher should have returned two authors, but returned only one.
That sounds like English with a french accent to my inner voice...

2022-05-10 21:50 UTC, Siedlerchr commented
I close this for the moment, until we find time to improve the algorithm

2022-05-10 21:50 UTC, closed without merging