Find Unlinked files should ignore Thumbs.db, etc
JabRef/jabref pull request #8800
Opened 2022-05-15 19:58 UTC by prashant1712

Fixes https://github.com/koppor/jabref/issues/373.

Reads the .gitignore file in the root directory of the library path and obeys it according to the option selected in the UI dialog box.

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
<img width="1440" alt="Screenshot 2022-05-16 at 5 09 16 AM" src="https://user-images.githubusercontent.com/26690114/168491466-f6398f45-1f2e-42e6-b6cc-c5d38514300b.png">

2022-05-15 21:02 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java
> +                int i = path.toString().lastIndexOf('.');
You can reuse FileUtil.getFileExtension() here

2022-05-15 21:03 UTC, Siedlerchr commented on CHANGELOG.md
> +- We added an extra option in the 'Find Unlinked Files' dialog view to ignore unnecessary files like Thumbs.db, DS_Store, etc. [#373](https://github.com/koppor/jabref/issues/373)
```suggestion
- We added an extra option in the 'Find Unlinked Files' dialog view to ignore unnecessary files like Thumbs.db, DS_Store, etc. [koppor#373](https://github.com/koppor/jabref/issues/373)
```

2022-05-16 11:23 UTC, prashant1712 commented
Thank you for your suggestions. I will make the changes and commit it soon.

2022-05-16 19:39 UTC, calixtus commented on .gitignore
> +AAGenerator.cpp
this seems to be an artifact of another programming project?

2022-05-16 19:39 UTC, calixtus commented on .gitignore
> +data.tsv
also an artifact?

2022-05-16 20:03 UTC, calixtus requested changes
Great work. Some minor remarks, but looks already very good!

2022-05-16 20:03 UTC, calixtus commented on src/main/java/org/jabref/gui/externalfiles/FileIgnoreUnlinkedFiles.java
> +    public static Set<String> getIgnoreFileSet() {
I'm really not a fan of these static methods. Keep the scope small and only use statics or globals if really neccessary. I think this method rather belongs in the UnlinkedFilesDialogViewModel

2022-05-19 17:35 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/externalfiles/FileFilterUtils.java
> +    private static Set<String> FILEIGNORESET = null;
I would initliaize this e.g = new HashSet<>() to prevent potentital NPEs

2022-05-19 18:01 UTC, Siedlerchr commented
I did some refactorings to improve the code:
1. I moved down the reading of the ignore file from the dialog view model to the "logic" as it does not really depend on the dialog.
2. A general thing: Try to pass dependencies always down through the constructor (Inversion of Control). This makes it easier to test or mock the class and provides better encapsulation
3. I added a check to make sure the gitignore File is there before reading it. Relying on exceptions for control flows is a bad design idea. As the name implies, exceptions should be there when something unusual happens.


Now I would like you to add a test for new method FileFilterUtils and maybe as well for the UnlinkedFilesCrawler. That would be cool

2022-05-21 09:55 UTC, prashant1712 commented
@Siedlerchr Thank you for your help. Really appreciate the refactoring to improve the code, helped us in understanding the code better. One small thing, you changed the code to read the .gitignore file from the system of the user which i don't think is appropriate in our case. I'm changing it back to read it from the source directory of Jabref. Do let us know your opinion on this.

2022-05-21 13:41 UTC, Siedlerchr commented
Yeah, that's one thing I wasn't sure about. I thought it makes sense to check the folder you selected to search for the files and the subfolders if there is any gitignore file inside and use this then?

2022-05-22 04:47 UTC, prashant1712 commented
Yeah, i'm not really sure what to do now. Which scenario are we going to take: Searching for the .gitignore file in the directory selected by the user or picking up the .gitignore file from the source directory of JabRef. We initially thought that it makes sense to ignore the extensions and file names mentioned in the .gitignore file of JabRef as it gives a consistent behaviour across all users but I'm quite confused right now and would really appreciate a solution to this.

2022-05-22 15:27 UTC, Siedlerchr commented
Let's ask @koppor  as it was his issue...

2022-05-23 13:17 UTC, calixtus commented on src/main/java/org/jabref/gui/externalfiles/UnlinkedFilesCrawler.java
>  import java.nio.file.Path;
I just mentioned you are mixing pre-java7-io api and nio. Is there a special reason?

2022-05-23 18:03 UTC, koppor commented
> Yeah, i'm not really sure what to do now. Which scenario are we going to take: Searching for the .gitignore file in the directory selected by the user

Yes, do this.

**In addition** following files / directories are always ignored:

- `.git`
- `Thumbs.db`

This list is hard-coded in Java. No additional text file. No option for configuration.

2022-05-25 11:55 UTC, prashant1712 commented
Understood. Thank you @koppor for the clarification. I'll make the changes accordingly.

2022-05-30 18:40 UTC, Siedlerchr commented
Please also include .DS_Store (A kind of desktop.ini equivalent for mac) in the default ignored files

2022-06-04 12:43 UTC, calixtus commented
Any update here?

2022-06-05 08:37 UTC, prashant1712 commented
Hi @calixtus, i am recovering from a medical condition right now. Will complete the changes when i'm recovered. Thank you for understanding.

2022-06-05 21:45 UTC, calixtus commented
Of course, get well soon.

2022-06-20 21:28 UTC, koppor commented
@prashant1712 In each dev call, we choose a PR (more or less randomly) to finish it. Today, we worked 2 hours on this one. the intermediate result is there. However, the tests still fail. We need to continue here.

2022-06-27 21:12 UTC, merged