Fix the issue:A particular empty entry can be added without warning message#8645
JabRef/jabref pull request #8981
Opened 2022-07-15 11:54 UTC by xiaoyanghuo

This is group14 from the course "Open Source Development".

We fixed the issue [#8645,](https://github.com/JabRef/jabref/issues/8645) which shows that a particular empty entry can be added without warning message.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-07-15 12:42 UTC, xiaoyanghuo commented
Although what we submitted was about that thing, it had flaws. Because we don't understand this task very well, we didn't find the relevant dialog in debugging。
![image](https://user-images.githubusercontent.com/78256591/179225078-8f46484f-c78f-42a9-ad28-7cfd915e1d45.png)

2022-07-15 15:57 UTC, xiaoyanghuo commented
Thank you for your attention!

2022-09-14 20:19 UTC, koppor requested changes
Some small comments.

Otherwise, looks good.

The issue https://github.com/JabRef/jabref/issues/8645 is NOT fixed. The PR at hand just changes the defaults of JabRef, but a user might not want this behavior.

JabRef really (!) has to remove the empty entry before save.

2022-09-14 20:19 UTC, koppor commented on CHANGELOG.md
> +- We fixed an issue where A particular empty entry can be added without warning message [#8645](https://github.com/JabRef/jabref/issues/8645)
```suggestion
- We fixed an issue where a particular empty entry can be added without warning message. [#8645](https://github.com/JabRef/jabref/issues/8645)
```

2022-09-14 20:19 UTC, koppor commented on CHANGELOG.md
> +- Now all the entries with no empty citationkey will be detected by "Check integrity",and a test of it has been added.
```suggestion
- Now all the entries with no empty citationkey will be detected by "Check integrity". 
```

"test" is not user-visible. Thus, removed.

2022-09-14 20:21 UTC, koppor commented
A follow-up PR should REALLY add a test case for the BibTeX shown in https://github.com/JabRef/jabref/issues/8645

2022-09-17 11:34 UTC, calixtus commented
I personally am against the change of the default value, since a user might just want to test JabRef and would not expect JabRef to change all of his entries by default when saving again. Looking for the right pref option is just annoying for first time users.

Also this PR does not fix the issue.

2022-09-17 11:36 UTC, calixtus commented
Test could be reused though.

2022-09-17 13:38 UTC, calixtus commented on src/main/java/org/jabref/logic/integrity/CitationKeyChecker.java
> + * Currently checks the key all the time.
Past is not of interest for the current implementation. Past can be viewed in git history.

2022-11-22 19:21 UTC, ThiloteE commented
@xiaoyanghuo thank you and your group for this pr, I hope you have learned something from it.

Closing this pr, because as far as I can see, it is in an incomplete state, there is inactivity and I would like to reduce the number of open pull-requests. Feel free to reopen, if you ever feel like wanting to continue working on it.

2022-11-22 19:21 UTC, closed without merging