Add log for ignored excepton
JabRef/jabref pull request #9302
Opened 2022-10-24 14:17 UTC by VernonKwa

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-11-08 21:56 UTC, calixtus commented
Thanks four your PR. What's the status here? Is this ready for review?

2022-11-18 10:10 UTC, ThiloteE commented
yes, there was a comment asking for review in the issue this pr will fix.

2022-12-05 19:59 UTC, koppor requested changes
Some minor comments. Please also fix merge conflicts.

2022-12-05 19:59 UTC, koppor commented on src/main/java/org/jabref/gui/groups/GroupDialogViewModel.java
> +                        // Ignored
This can be removed

2022-12-05 19:59 UTC, koppor commented on src/main/java/org/jabref/logic/importer/util/FileFieldParser.java
>                  field = new LinkedFile(entry.get(0), entry.get(1), entry.get(2));
Why renamed and not logged?

2022-12-05 19:59 UTC, koppor commented on src/main/java/org/jabref/logic/importer/util/FileFieldParser.java
> +                    // Ignored
Please rename `e` to `ignored` and remove the comment

2022-12-05 19:59 UTC, koppor commented on src/main/java/org/jabref/logic/remote/server/RemoteListenerServer.java
> +            LOGGER.warn("Unable to close server socket!", e);
No exclamation mark

2022-12-05 19:59 UTC, koppor commented on src/main/java/org/jabref/logic/util/BuildInfo.java
>              // nothing to do -> default already set
Please keep "ignored"

2022-12-19 20:18 UTC, merged