Removed BibTeX file type and included HTML and Markdown types
JabRef/jabref pull request #9318
Opened 2022-10-28 05:15 UTC by Simone-Thai

Fixes [koppor/#547](https://github.com/koppor/jabref/issues/547?fbclid=IwAR2TtODoezs2F35XsIifHrrVOXfKlSTWcAQACgjDp5JJQGbfcJXjnZxSBEU) by removing the BibTeX dropdown option. I have also added HTML and Markdown filtering options as they are commonly used standard files.    

<img width="626" alt="Screen Shot 2022-10-28 at 4 05 13 pm" src="https://user-images.githubusercontent.com/110802893/198507879-5d4fe8b1-90fc-4a8d-a346-8a5916251366.png">

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-10-28 05:16 UTC, Simone-Thai commented
I accidentally created a pull request in my own repository. Here is the link to it:
https://github.com/Simone-Thai/jabref/pull/2

2022-10-28 09:09 UTC, Simone-Thai commented
I've also added a basic file icon to the dropdown.
<img width="381" alt="image" src="https://user-images.githubusercontent.com/110802893/198550166-b65cdf5f-26d3-48e6-b10d-080167fa3d35.png">

2022-10-28 15:55 UTC, Siedlerchr commented on CHANGELOG.md
> +- We added HTML and Markdown files to Find Unlinked Files and removed BibTex. Markdown was added as a StandardFileType and StandardExternalFileType [koppor#547](https://github.com/koppor/jabref/issue
```suggestion
- We added HTML and Markdown files to Find Unlinked Files and removed BibTex. [koppor#547](https://github.com/koppor/jabref/issues/547)
```
The changelog is targeted to end users, so implementation details are not necessary here

2022-10-28 19:47 UTC, Siedlerchr commented
Please have a look at the failing unit and checkstyle tests

2022-10-29 02:40 UTC, Simone-Thai commented
The Test `ExternalFileTypesTest` was failing because it didn't include markdown so I've added it in.

2022-10-29 08:44 UTC, Siedlerchr requested changes

2022-10-29 08:44 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/externalfiletype/StandardExternalFileType.java
> +    MARKDOWN("Markdown", "md", "application/x-latex", "emacs", "emacs", IconTheme.JabRefIcons.FILE_TEXT);
https://stackoverflow.com/a/25812177/3450689
The mime type needs to adjusted

2022-10-30 14:09 UTC, calixtus approved these changes
Looks good to me

2022-10-30 19:39 UTC, Siedlerchr approved these changes

2022-10-30 19:39 UTC, merged