added an option in preferences/groups to change the default the hierarchical context
JabRef/jabref pull request #9344
Opened 2022-11-03 03:36 UTC by roryoday

added an option in preferences/groups to change the default the hierarchical context. Options are Union/Intersection/Independent.  Issue #9141 

- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [x] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-11-04 17:16 UTC, ThiloteE commented
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>

2022-11-05 17:10 UTC, Siedlerchr commented
Please have a look at  the failing checkstyle tests or reviewdog

2022-11-08 21:40 UTC, calixtus requested changes
Hi, thanks for your interest in JabRef programming. I looked quickly into your changes. Please configure checkstyle according to our code style standards. Please look into our Getting Started guide here (https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.html),

Plase integrate the requested changes, so we can discuss merging.

2022-11-08 21:40 UTC, calixtus commented on src/main/java/org/jabref/model/groups/GroupHierarchyType.java
> +    }
This should be implemented as an constructor argument for the enum e.g.  `INDEPENDENT("Independent")` and be localized. Open/closed design principle.

2022-11-08 21:40 UTC, calixtus commented on src/test/java/org/jabref/gui/groups/GroupCreateTest.java
> +    }
I really don't get what you want to test here?
The constructor of GroupNodeViewModel?
This test seems superfluous to me, especially it does not seem to be related to any code change in the PR. The thing that should be tested is if someone clicks in the UI an "add new group" the default GroupHierarchyType is selected.

2023-01-20 16:06 UTC, ThiloteE commented
closing this, as there is a lack of response and to reduce the number of open pull-requests.
@roryoday  Feel free to reopen, if you think you will continue to work on this.

2023-01-20 16:06 UTC, closed without merging