Get full text
JabRef/jabref pull request #9437
Opened 2022-12-07 23:26 UTC by NiD133

[#568](https://github.com/koppor/jabref/issues/568)
![image](https://user-images.githubusercontent.com/91547740/206319081-81242ca6-a378-495f-9720-5836b2bee36d.png)

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2022-12-18 23:53 UTC, koppor requested changes
Please fix checkstyle - and don't pass Optionals

2022-12-19 20:39 UTC, koppor requested changes

2022-12-19 20:39 UTC, koppor commented on CHANGELOG.md
> +- We fixed an issue when using an unsafe character in the citation key, the auto-linking feature fails to link files. [#9267](https://github.com/JabRef/jabref/issues/9267)
Remove this line, because we meanwhile released a new version. (Keep line 30)

2022-12-19 20:39 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModel.java
> +        } else {
If `downloadFile` fails, JabRef should still fireup the BackgroundTask.

Maybe have `downloadFile` returning a `Boolean`? `true` if it went fine, `false` if it did not. 

here then if the result is `false`, start the Background task.

2022-12-21 21:19 UTC, Siedlerchr requested changes

2022-12-21 21:19 UTC, Siedlerchr commented on src/test/java/org/jabref/gui/fieldeditors/LinkedFilesEditorViewModelTest.java
> +        importFormatPreferences = mock(ImportFormatPreferences.class, Answers.RETURNS_DEEP_STUBS);
I think this whole setup code can be removed as you don't use it anywhere and the preferencesService returns deep stubs

2022-12-22 10:04 UTC, NiD133 commented
@Siedlerchr I've removed the setup code, sorry touch the Resolve conversation

2023-02-25 17:50 UTC, Siedlerchr approved these changes
Works so far. Better than nothing

2023-02-27 21:02 UTC, merged