Fix deletion of multiple files should show one confirmation dialog
JabRef/jabref pull request #9573
Opened 2023-01-19 07:36 UTC by shreverr

Fixes #9473 

Moved code of delete dialog from `LinkedFileViewModel` to `LinkedFilesEditorViewModel`.
Made a separate method in 'LinkedFilesEditorViewModel' for deleting multiple files `deleteFiles`.
Made a 'getDir' method in `LinkedFileViewModel` to get the path of file.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
---
Deleting single File

![image](https://user-images.githubusercontent.com/108074738/213381174-c200472e-adec-432b-9832-c01301d6be50.png)

Deleting Multiple Files

![image](https://user-images.githubusercontent.com/108074738/213381824-3acc9d06-8923-409a-9a52-0cbfe47b989f.png)

2023-01-21 23:37 UTC, calixtus requested changes
Hi, thanks for your interes in JabRef development and your proposed changes. I took a quick look into it and am a bit concerned that the changes do not really work well as they are right now.
I believe the whole delete stuff should move to a new class extending SimpleCommand to make this undoable eventually. This command could then be called at any place and should not depend on JavaFX dialog buttons.

Thanks!

2023-01-21 23:37 UTC, calixtus commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +        Optional<Path> file = getDir();
Please avoid passing Optionals as arguments.
Why at all is a ButtonType object being used in the ViewModel?
This does not seem right at all. The ViewModel should not have to deal with the ui elements, this breaks the mvvm pattern. Please use primitives here.

2023-01-21 23:37 UTC, calixtus commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +    public Optional<Path> getDir() {
Please don't use abbreviations. Try to be more concise, what directory is being looked for?

2023-02-11 21:51 UTC, Siedlerchr commented
Closing this PR due to inactivity :zzz: 
Please reopen the PR if you plan to continue working on this

2023-02-11 21:51 UTC, closed without merging