Rewrite code of MedlineImporter
JabRef/jabref pull request #9673
Opened 2023-03-16 06:29 UTC by aqurilla

This fixes https://github.com/JabRef/jabref/issues/9536 by rewriting the `org.jabref.logic.importer.fileformat.MedlineImporter` class to use a StAX-Parser, and removes all JAXB dependencies from the class. The corresponding xjc task is also removed from `build.gradle`.

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [x] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [x] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-03-16 07:41 UTC, Siedlerchr commented
Thanks! Looks good! can you take a look at https://github.com/JabRef/jabref/issues/4273 as well?

2023-03-16 23:03 UTC, koppor requested changes
Thank you so much for working on this! 🎉

I have micro nitpicks 😇 - otherwise, looks good!

2023-03-16 23:03 UTC, koppor commented on src/main/java/org/jabref/logic/importer/fileformat/medline/ArticleID.java
I was thinking whether there is really a need for these classes, but it seems, that is indeed necessary.

I quickly checked https://nipafx.dev/java-var-anonymous-classes-tricks/ (hint by @Siedlerchr), but I did not see a win making the code better.

2023-03-17 02:51 UTC, aqurilla commented on src/main/java/org/jabref/logic/importer/fileformat/MedlineImporter.java
> +        List<ArticleID> articleIDList = new ArrayList<>();
Thanks for you feedback! :) I'll make these changes

2023-03-17 04:05 UTC, aqurilla commented
I think the `AstrophysicsDataSystemTest` failed due to some network issues? I did not make any changes related to those files

2023-03-17 12:58 UTC, koppor commented
Yes, their servers return server error:

    java.io.IOException: org.jabref.logic.importer.FetcherServerException: Encountered HTTP Status Code 504

2023-03-18 04:15 UTC, aqurilla commented
I found that Abstract and Title xml elements containing italics, bold tags etc. were getting cut short, so updated the code to handle this. 
Agreed that MathML support should be a separate PR since it looks like it will require handling a large number of tags!

2023-03-18 09:12 UTC, koppor approved these changes
Think, it's an improvement and I go forward with merge.

Regarding the italics:

```html
The apolipoprotein E (
                        <i>APOE</i>) gene on chromosome
```

should get

```latex
The apolipoprotein E (\textit{APOE}) gene on chromosome
```

Since it are very rare cases of HTML tags, it should be "easy". Maybe, this can be implemented when converting MathML?

2023-03-18 09:12 UTC, merged