Improved error message when downloading a file fails #9826
JabRef/jabref pull request #9838
Opened 2023-05-04 06:54 UTC by yerraga

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

2023-05-04 07:26 UTC, koppor commented
@yerraga Thank you for the contribution. Can you please fix checkstyle? See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-13-code-style.html for details. Please also use `{}` at the logger (instead of string concatenation)

I think, the whole thing should be tested. Can you dive into WireMock to setup mocking the remote servers - so that each exception path in LinkedFileViewModel is tested? https://wiremock.org/docs/junit-jupiter/

2023-05-04 07:54 UTC, ThiloteE commented
To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>

2023-05-14 07:51 UTC, koppor requested changes

2023-05-14 07:51 UTC, koppor commented on src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java
> +                    dialogService.showErrorDialogAndWait(Localization.lang("Error downloading from URL"),
The second part is also shown to the user
. Thus, that needs to be localized too. It is OK for me to include the server error here.

2023-06-10 12:12 UTC, Siedlerchr commented
What is the status here? Are you planning to fix the compile errors to get it working?

2023-06-19 19:06 UTC, calixtus commented
Closing this issue due to inactivity :zzz: 
Please reopen a PR if you intend to continue on this issue. We really liked your idea and draft.

2023-06-19 19:06 UTC, closed without merging