Fixes Web icon also for ISBN
JabRef/jabref pull request #9879
Opened 2023-05-13 15:40 UTC by mkumar09

[Fixes #9819 ](https://github.com/JabRef/jabref/issues/9819)

Description : The ISBNs where not having a URL standard field in the BiBEntry. So made the changes to add the URL field in the BiBEntry retrieved from ISBNFetcher.

```[tasklist]
### Compulsory checks
- [x] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [x] Manually tested changed features in running JabRef (always required)
- [x] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

2023-05-14 07:41 UTC, koppor commented
Thank you for working on this. Please rethink the solution: JabRef knows the URL based on the precense of an ISBN. The link can be changed in future. Maybe one wants to open books on Amazon or the University Library. Then one does not want to change all bib files. If you opt for Amazon and I for university, the Bib file would change back and forth.

Thus, it is an UI issue. Check the main table how the URL is filled. I think, we have a field property ISBN, which can be used.

2023-05-14 07:42 UTC, koppor requested changes
The implemention should work on the view not on the Bib data.

2023-05-14 18:59 UTC, calixtus commented
You can take a look at BibEntryTableViewModel::createLinkedIdentifiersBinding .
I believe this would be a good starting point for a fix.

2023-05-16 14:03 UTC, koppor commented
I can't see a diff. Would be good to do a commit. Then, one can also try out locally.

2023-05-16 19:59 UTC, koppor commented
@mkumar09 Did you try your solution? 

Two things to check: 

A) does the web column display the icon if the ISBN is present?

![image](https://github.com/JabRef/jabref/assets/1366654/358a006d-19ad-4d91-b257-53f56f58a38c)

B) Does a click on that icon open the page?

---

I think, your code snippet misses the first requirement.

2023-05-19 16:57 UTC, mkumar09 commented
> @mkumar09 Did you try your solution?
> 
> Two things to check:
> 
> A) does the web column display the icon if the ISBN is present?
> 
> ![image](https://user-images.githubusercontent.com/1366654/238758459-358a006d-19ad-4d91-b257-53f56f58a38c.png)
> 
> B) Does a click on that icon open the page?
> 
> I think, your code snippet misses the first requirement.

Hey @koppor. I checked the solution with this code snippet. It fulfills the first requirement,i.e, to show the link icon but for some reason, clicking on it doesn't open the page.

2023-05-19 17:27 UTC, Siedlerchr commented
Best is to push your code so we can have a chance to see all changes.

2023-05-19 17:44 UTC, closed without merging