Add editor pattern test in BracketedPatternTest
JabRef/jabref pull request #9946
Opened 2023-05-23 14:28 UTC by chiao26168

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

The existing test class, org.jabref.logic.citationkeypattern.BracketedPatternTest.java, currently lacks coverage for editor patterns. To address this gap, I have added a new test method, testEditorFieldMarkers() to ensure that the editor pattern functions correctly.

During the execution of testEditorFieldMarkers(), one test case failed. The input provided was "'New', '[edtr3_1]', 'Isaac Newton'", and the expected output was 'New'. However, the actual output was null.

<img width="237" alt="Screen Shot 2023-05-23 at 7 01 36 AM" src="https://github.com/JabRef/jabref/assets/72399061/f5325c88-15f0-48e7-9ad7-9efa1393d022">

(output of the failed test case)

The source of the error can be found in org.jabref.logic.citationkeypattern.BracketedPattern. 
As stated in [Customize the citation key generator](https://docs.jabref.org/setup/citationkeypatterns), when the pattern matches "edtrN_M", the citation key should consist of the first N characters of the Mth editor's last name. 

Here is a screenshot highlighting the problem in the source code:
<img width="794" alt="Screen Shot 2023-05-23 at 7 10 10 AM" src="https://github.com/JabRef/jabref/assets/72399061/054e2666-dd3a-4c35-b895-315d2190d6e5">

To fix this issue, the following return statement should be used

```
return authNofMth(editorList,
                            Integer.parseInt(nums[0]),
                            Integer.parseInt(nums[1]));
```

2023-05-23 14:30 UTC, Siedlerchr commented
Thank you very much! Please go ahead and fix this as well :)

2023-05-24 16:30 UTC, k3KAW8Pnf7mkmdSMPHz27 requested changes
Overall this looks very good, and I love the detailed description! I am slightly disturbed that the `authNofMth` error seems to have been here since 2017, so test cases for this are definitively needed :scream: 

Remaining
- I am not sure about one of the test cases. Could you write down your thoughts regarding it, or if we have a similar test case in a different part of the code, reference it? I am hesitant to include it because I believe it might be a misuse of the editors' field, in which case all bets are off, and there isn't a right or wrong behavior of JabRef
- Would you mind fixing the code style check complaints? It is much less important in a test case, but since it is only complaining about new lines
- Since the behavior is changing, please add an entry to the change list, even if it is now the correct behavior as described in the documentation

2023-05-30 16:25 UTC, Siedlerchr commented on src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java
> +            "'Agency', '[editors]', 'European Union Aviation Safety Agency'",
Not malformed, but it does not make sense to have a corporate author without curly brackets-

2023-05-30 21:27 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java
> +            "'Agency', '[editors]', 'European Union Aviation Safety Agency'",
@Siedlerchr you agree that this one particular test should be removed?

2023-05-31 19:06 UTC, Siedlerchr commented on src/test/java/org/jabref/logic/citationkeypattern/BracketedPatternTest.java
> +            "'Agency', '[editors]', 'European Union Aviation Safety Agency'",
```suggestion

```

2023-05-31 19:08 UTC, Siedlerchr commented
@chiao26168  can you please add a changelog entry?

2023-05-31 19:28 UTC, chiao26168 commented
> @chiao26168 can you please add a changelog entry?

Should I add two entries, one for adding the test case and the other for fixing the error?

2023-05-31 20:28 UTC, Siedlerchr commented
Changelog is intended for the end users so just one for the changed behavior/fix

2023-06-01 20:07 UTC, k3KAW8Pnf7mkmdSMPHz27 approved these changes
LGTM! We greatly appreciate the detailed description, the missing test-cases, detection of a bug, and fixing of the bug :sweat_smile:

2023-06-01 20:07 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on CHANGELOG.md
> +- We fixed an issue where the citation key pattern `[edtrN_M]` was not handled properly. [#9946](https://github.com/JabRef/jabref/pull/9946)
```suggestion
- We fixed an issue where the citation key pattern `[edtrN_M]` returned the wrong editor. [#9946](https://github.com/JabRef/jabref/pull/9946)
```

Nitpick/Opinionated: Explains it a bit more and is easier to understand. The PR is accepted from my point of view anyway.

2023-06-02 13:35 UTC, Siedlerchr approved these changes

2023-06-02 13:35 UTC, merged

2023-06-02 13:35 UTC, Siedlerchr commented
Thanks again for the tests and finding these bugs!