Add new menu entry to remove braces from selection, aka unprotect it.
JabRef/jabref pull request #9968
Opened 2023-06-01 20:47 UTC by BeeJay28

### Mandatory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2023-06-01 21:28 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/fieldeditors/contextmenu/ProtectedTermsMenu.java
> +            String selectedText = textInputControl.getSelectedText();
Just use the UnprotectTermsFormatter

2023-06-05 18:54 UTC, Siedlerchr submitted a review, later dismissed

2023-06-06 06:04 UTC, koppor commented
The PR misses a screenshot:

![image](https://github.com/JabRef/jabref/assets/1366654/0a334ea0-a718-4114-84a2-d89a00cd3457)

It works there, but does not work if nothing is selected:

![image](https://github.com/JabRef/jabref/assets/1366654/cd810795-97f3-4cd1-9ebc-39ed29e107e7)

Three options:

a) gray out option if nothing is selected
b) Unprotect ALL if clicked
c) change text to "Unprotect" if nothing is selected and unprotect everything when clicked

2023-06-06 06:05 UTC, koppor requested changes
It does not behave properly when nothing is selected. See comments.

Minor: I had to fix a CHANGELOG merge error.

2023-06-06 08:04 UTC, BeeJay28 commented
> 
I was unsure of what it should exactly do if nothing is selected, so I just left it at the easiest option. Thanks for the feedback, I'll get on it.
And thank you for the screenshot. Tbh, I just had issues screenshotting while having the right click menu up (it would automatically close before capture). Thank you for that too 😅

2023-06-06 08:14 UTC, koppor commented
> And thank you for the screenshot. Tbh, I just had issues screenshotting while having the right click menu up (it would automatically close before capture). Thank you for that too 😅

I am using Greenshot on Windows with Hotkey <kbd>Ctrl</kbd>+<kbd>F1</kbd> and that works most of the time. I also have experiences using GIMP, where one can say: Take a screenshot in 10 seconds. Then, one only needs "patience".

Thank you for continuing working on this!

2023-06-06 13:07 UTC, BeeJay28 commented
> Three options:
> 
> a) gray out option if nothing is selected b) Unprotect ALL if clicked c) change text to "Unprotect" if nothing is selected and unprotect everything when clicked

I picked option a)

2023-06-06 15:17 UTC, koppor approved these changes

2023-06-06 15:26 UTC, Siedlerchr approved these changes

2023-06-06 15:26 UTC, merged